package com.github.xuse.querydsl.r2dbc.entity;

import java.sql.Types;
import java.util.Date;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.UnsavedValue;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.Comment;
import com.github.xuse.querydsl.annotation.dbdef.Key;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;
import com.github.xuse.querydsl.sql.ddl.ConstraintType;

import lombok.Data;

@Data
@TableSpec(name="school",primaryKeys="id",collate = "utf8mb4_general_ci",
keys = {
		@Key(path= {"code"},type=ConstraintType.UNIQUE),
		@Key(path= {"content"},type=ConstraintType.KEY),
	}
)
@Comment("table of school.")
public class School {
	
	@ColumnSpec(autoIncrement = true,type = Types.INTEGER,unsigned = true,nullable = false)
	@Comment("primary key，auto increment.")
	private int id;
	
	@ColumnSpec(type = Types.VARCHAR,size=64,nullable = false,defaultValue = "''")
	@Comment("The code of school. unique.")
	private String code;
	
	@ColumnSpec(name="asset_name",size=128,nullable = false)
	@Comment("The name of the school.")
	private String name;
	
	@ColumnSpec(size=16384)
	@Comment("school comments.")
	private String content;
	
	@ColumnSpec()
	@AutoGenerated(GeneratedType.CREATED_TIMESTAMP)
	@Comment("create time of the record.")
	private Date created;
	
	@ColumnSpec()
	@AutoGenerated(GeneratedType.UPDATED_TIMESTAMP)
	@Comment("update time of the record.")
	private Date updated;
	
	@ColumnSpec(type=Types.INTEGER,nullable = false,unsigned = true)
	@UnsavedValue(UnsavedValue.MinusNumber)
	private int volume;

}
