package com.github.xuse.querydsl.r2dbc.entity;

import java.util.Date;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.UnsavedValue;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;

import lombok.Data;

@TableSpec(name="user",primaryKeys = "id")
@Data
public class User {
	@UnsavedValue(UnsavedValue.ZeroAndMinus)
	@ColumnSpec(autoIncrement = true,nullable = false)
	private long id;
	
	@ColumnSpec(nullable = false)
	private String name;
	
	@ColumnSpec(nullable = false)
	private String uid;
	
	@ColumnSpec(nullable = false)
	@AutoGenerated(value = GeneratedType.CREATED_TIMESTAMP)
	private Date created;
	
	@ColumnSpec(nullable = false)
	@AutoGenerated(value = GeneratedType.UPDATED_TIMESTAMP)
	private Date modified;
	
	@ColumnSpec(size = 64)
	private String email;
}
