package com.github.xuse.querydsl.sql.dialect;

import com.querydsl.core.types.Operator;

/**
 * <h2>English:</h2>
 * Enumeration of database-specific features used to control DDL generation behavior.
 * <h2>Chinese:</h2>
 * 数据库特有功能枚举，用于控制DDL生成行为。部分特性尚未启用，后续将清理。
 */

public enum SpecialFeature implements Operator{
	/**
	 * <h2>English:</h2> For Oracle compatibility.
	 * <h2>Chinese:</h2> Oracle兼容用
	 */
	HAS_CRLF_IN_DEFAULT_VALUE_EXPRESSION,
	
	/**
	 * <h2>English:</h2> Multiple columns can be operated in a single ALTER TABLE statement (MySQL and Oracle).
	 * <h2>Chinese:</h2> 在执行ALTER TABLE语句的时候一次可以操作多个列 (MySQL And Oracle)
	 */
	MULTI_COLUMNS_IN_ALTER_TABLE,
	
	/**
	 * <h2>English:</h2> Independent COMMENT statement (First for PostgreSQL).
	 * <h2>Chinese:</h2> 独立的COMMENT语句 (First for postgres)
	 */
	INDEPENDENT_COMMENT_STATEMENT,
	
	/**
	 * <h2>English:</h2> Partition creation is an independent statement (First for PostgreSQL).
	 * <h2>Chinese:</h2> 分区创建是独立语句(First for Postgresql)
	 */
	INDEPENDENT_PARTITION_CREATION,
	
	/**
	 * <h2>English:</h2> Partition key must be part of the primary key (First for MySQL).
	 * <h2>Chinese:</h2> 分区字段必须是主键字段之一(First for MySQL)
	 */
	PARTITION_KEY_MUST_IN_PRIMARY,
	
	/**
	 * <h2>English:</h2> Cannot create constraints directly on partitioned tables (First for PostgreSQL).
	 * <h2>Chinese:</h2> 分区表上不能直接创建约束(First for Postgresql)
	 */
	NO_KEYS_ON_PARTITION_TABLE,
	
	/**
	 * <h2>English:</h2> Let JDBC decide the auto-generated key column, do not specify manually (First for Derby).
	 * <h2>Chinese:</h2> 由JDBC决定返回的自增键字段，不要人工指定。(First for Derby) 
	 */
	PREFER_AUTOGENERATED_KEYS
	;
	
	@Override
	public Class<?> getType() {
		return null;
	}
	
}
