package com.github.xuse.querydsl.sql.dialect;

import com.querydsl.core.types.Operator;

/**
 * 从我的上一个框架复制来的代码。大部分都还没有用到，后续将清理掉不再使用的特性
 */

public enum SpecialFeature implements Operator{
	/**
	 * Oracle兼容用
	 */
	HAS_CRLF_IN_DEFAULT_VALUE_EXPRESSION,
	
	/**
	 * 在执行ALTER TABLE语句的时候一次可以操作多个列 (MySQL And Oracle)
	 */
	MULTI_COLUMNS_IN_ALTER_TABLE,
	
	/**
	 * 独立的COMMENT语句 (First for postgres)
	 */
	INDEPENDENT_COMMENT_STATEMENT,
	
	/**
	 * 分区创建是独立语句(First for Postgresql)
	 */
	INDEPENDENT_PARTITION_CREATION,
	
	/**
	 * 分区字段必须是主键字段之一(First for MySQL)
	 */
	PARTITION_KEY_MUST_IN_PRIMARY,
	
	/**
	 * 分区表上不能直接创建约束(First for Postgresql)
	 */
	NO_KEYS_ON_PARTITION_TABLE,
	
	/**
	 * 由JDBC决定返回的自增键字段，不要人工指定。(First for Derby) 
	 */
	PERFER_AUTOGENERATED_KEYS
	;
	
	@Override
	public Class<?> getType() {
		return null;
	}
	
}
