package com.github.xuse.querydsl.util;

import java.io.Serializable;
import java.sql.Types;
import java.time.Instant;
import java.util.Date;
import java.util.Map;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.CustomType;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.UnsavedValue;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.Comment;
import com.github.xuse.querydsl.annotation.dbdef.Key;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;
import com.github.xuse.querydsl.datatype.JSONObjectType;
import com.github.xuse.querydsl.lambda.DateTimeLambdaColumn;
import com.github.xuse.querydsl.lambda.LambdaTable;
import com.github.xuse.querydsl.lambda.NumberLambdaColumn;
import com.github.xuse.querydsl.lambda.StringLambdaColumn;
import com.github.xuse.querydsl.sql.ddl.ConstraintType;

import lombok.Data;

/**
 * A database object without Q* class.
 */
@Data
@TableSpec(name="ca_foo",primaryKeys="id",collate = "utf8mb4_general_ci",
keys = {
		@Key(path= {"code"},type=ConstraintType.UNIQUE),
		@Key(path= {"content"},type=ConstraintType.FULLTEXT,allowIgnore = true),
	}
)
@Comment("Test table for Foo.")
public class Foo implements Serializable {
	private static final long serialVersionUID = 1L;

//	public static final LambdaTable<Foo> table=()->Foo.class;
//	
//	public static final NumberLambdaColumn<Foo,Long> _id=Foo::getId;
//	
//	public static final StringLambdaColumn<Foo> _content=Foo::getContent;
//	
//	public static final DateTimeLambdaColumn<Foo,Instant> _created=Foo::getCreated;
//	
//	public static final DateTimeLambdaColumn<Foo,Date> _updated=Foo::getUpdated;
//	
//	public static final NumberLambdaColumn<Foo,Integer> _version=Foo::getVersion;
	
	@ColumnSpec(autoIncrement = true,type = Types.BIGINT,unsigned = true,nullable = false)
	@Comment("primary key，auto increment.")
	private long id;
	
	@ColumnSpec(size=16384)
	@Comment("Asset's comments.")
	private String content;
	
	@ColumnSpec()
	@AutoGenerated(GeneratedType.CREATED_TIMESTAMP)
	@Comment("create time of the record.")
	private Instant created;
	
	@ColumnSpec()
	@AutoGenerated(GeneratedType.UPDATED_TIMESTAMP)
	@Comment("update time of the record.")
	private Date updated;
	
	@ColumnSpec(type=Types.INTEGER,nullable = false,unsigned = true,defaultValue = "1")
	@UnsavedValue(UnsavedValue.ZeroAndMinus)
	@AutoGenerated(GeneratedType.VERSION)
	private int version;
	
	@ColumnSpec(type=Types.VARCHAR,size = 1024)
	@CustomType(JSONObjectType.class)
	private Map<String,String> ext;
	
	@ColumnSpec(type=Types.BIT)
	private Boolean init;
}
