package com.github.xuse.querydsl.annotation;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * 写入数据库时给一些字段自动赋值。当使用inseret或update的populate方法时会自动生效
 * @author jiyi
 *
 */
@Target({ FIELD })
@Retention(RUNTIME)
public @interface AutoGenerated {
	/**
	 * 自动生成类型
	 * @return
	 */
	GeneratedType value();
	
	/**
	 * 如果传入的数据不为空，是否用生成的值覆盖
	 * @return
	 */
	boolean overwrite() default false;
	
	/**
	 * 参数
	 * @return
	 */
	String[] params() default {};
}
