package com.github.xuse.querydsl.sql.column;

import java.lang.annotation.Annotation;

import com.github.xuse.querydsl.annotation.GeneratedType;

final class AutoGeneratedImpl implements com.github.xuse.querydsl.annotation.AutoGenerated {
	private final GeneratedType type;
	private final boolean overwrite;
	private final String[] params;
	private final boolean writeback;

	AutoGeneratedImpl(GeneratedType type, boolean overwrite, boolean writeback, String[] params) {
		boolean canWriteback = (type != GeneratedType.CREATED_TIMESTAMP && type != GeneratedType.UPDATED_TIMESTAMP);
		this.type = type;
		this.overwrite = overwrite;
		this.params = params;
		this.writeback = writeback && canWriteback;
	}

	public Class<? extends Annotation> annotationType() {
		return com.github.xuse.querydsl.annotation.AutoGenerated.class;
	}

	@Override
	public GeneratedType value() {
		return type;
	}

	@Override
	public boolean overwrite() {
		return overwrite;
	}

	@Override
	public String[] params() {
		return params;
	}

	@Override
	public boolean writeback() {
		return writeback;
	}
}