package com.github.xuse.querydsl.sql.column;

import java.lang.annotation.Annotation;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.querydsl.core.types.Path;
import com.querydsl.sql.types.Type;

/**
 * <h2>English:</h2>
 * Describes the model information of a database column mapped to a Java field.
 * <h2>Chinese:</h2>
 * 描述一个数据库列 映射到java字段上的模型信息。
 * @see PathMapping
 */
public interface ColumnMapping extends ColumnMetadataEx {

	Path<?> getPath();

	/**
	 * <h2>English:</h2> Check if the value is an unsaved value.
	 * <h2>Chinese:</h2> 判断传入的值是否为无效值（未设置的值）
	 *  @param value value
	 *  @return if the value is unsaved.
	 */
	boolean isUnsavedValue(Object value);

	/**
	 * <h2>English:</h2> Get the auto-generated value configuration, or null if not configured.
	 * <h2>Chinese:</h2> 获取自动生成值的配置，如果未配置则返回null
	 *   @return AutoGenerated
	 */
	AutoGenerated getGenerated();

	/**
	 * <h2>English:</h2> This field does not participate in insert operations.
	 * <h2>Chinese:</h2> 该字段不参与插入
	 *
	 *   @return if it is notInsert
	 */
	boolean isNotInsert();

	/**
	 * <h2>English:</h2> This field does not participate in update operations.
	 * <h2>Chinese:</h2> 该字段不参与更新
	 *
	 *   @return if it isNotUpdate
	 */
	boolean isNotUpdate();

	/**
	 * <h2>English:</h2> Java field name.
	 * <h2>Chinese:</h2> java字段名
	 *
	 *   @return java字段名
	 */
	String fieldName();

	/**
	 * <h2>English:</h2> Get the Java field type.
	 * <h2>Chinese:</h2> 获得Java字段的类型
	 *   @return field type
	 */
	Class<?> getType();

	/**
	 * <h2>English:</h2> Get annotations on the field.
	 * <h2>Chinese:</h2> 获得添加在字段上的注解
	 * @param <T> The type of target object.
	 * @param clz clz
	 * @return annotations
	 */
	<T extends Annotation> T getAnnotation(Class<T> clz);

	/**
	 * <h2>English:</h2> Return the custom type mapping.
	 * <h2>Chinese:</h2> 返回自定义映射类型
	 *   @return CustomType def.
	 */
	Type<?> getCustomType();

	/**
	 * <h2>English:</h2> Set the custom type mapping.
	 * <h2>Chinese:</h2> 设置自定义映射
	 *   @param t 自定义映射
	 */
	void setCustomType(Type<?> t);

	/**
	 * <h2>English:</h2> Write back the auto-generated value to the corresponding field of the bean.
	 * <h2>Chinese:</h2> 将自动生成的值回写到Bean对象的对应字段中
	 *  @param bean bean
	 *  @param value value
	 */
	void writeback(Object bean, Object value);
	
	boolean isAutoIncrement();
}
