package com.github.xuse.querydsl.sql.dml;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.github.xuse.querydsl.sql.RelationalPathEx;
import com.github.xuse.querydsl.sql.RelationalPathExImpl;
import com.github.xuse.querydsl.sql.column.ColumnMapping;
import com.querydsl.core.types.Expression;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.Template;
import com.querydsl.core.types.TemplateExpression;
import com.querydsl.sql.RelationalPath;
import com.querydsl.sql.types.Null;

/**
 * Helper class for resolving default values of NOT NULL columns in batch insert scenarios.
 * <p>
 * When using batch insert (populateBatch), all columns are explicitly included in the SQL statement.
 * If a bean field is null and the column is NOT NULL with a DEFAULT value, the database will reject
 * the insert because an explicit NULL is written instead of relying on the DEFAULT.
 * <p>
 * This helper pre-computes Java literal substitution values for NOT NULL columns that have simple
 * default value expressions (e.g., '', 0, 1). For complex expressions like CURRENT_TIMESTAMP,
 * no substitution is performed (those are typically handled by @AutoGenerated).
 *
 * <h2>中文</h2>
 * 批量插入时，所有列都会显式出现在SQL中。如果Bean字段为null且列定义为NOT NULL + DEFAULT，
 * 数据库会因为显式写入NULL而拒绝插入。此工具类预计算NOT NULL列的Java字面量替代值，
 * 在批量插入时自动将null替换为对应的默认值。
 */
public class DefaultValueHelper {

	private static final Logger log = LoggerFactory.getLogger(DefaultValueHelper.class);

	/**
	 * Strategy interface for parsing a SQL default value string into a typed Java object.
	 */
	interface TypeParser {
		/**
		 * Parse a raw string value into the target Java type.
		 * @param value the trimmed string value
		 * @return the parsed Java object
		 */
		Object parse(String value);

		/**
		 * Convert a Number to the target Java type.
		 * @param num the source number
		 * @return the converted value
		 */
		Object fromNumber(Number num);

		/**
		 * Get the zero/empty value for this type (used for AGGRESSIVE_DEFAULT strategy).
		 * For numeric types, returns 0; for boolean, returns false; for date/time types, returns null.
		 * <p>
		 * 获取此类型的零值/空值（用于 AGGRESSIVE_DEFAULT 策略）。
		 * 数字类型返回 0，布尔类型返回 false，日期时间类型返回 null。
		 * 
		 * @return the zero/empty value for this type
		 */
		default Object getZeroValue() {
			return fromNumber(0);
		}

		/**
		 * Get an alternative fallback value when the zero value is treated as "unsaved".
		 * For numeric types, returns 1; for boolean, returns true; for others, returns null.
		 * <p>
		 * 当零值被视为"未保存值"时，获取替代的兜底值。
		 * 数字类型返回 1，布尔类型返回 true，其他类型返回 null。
		 * 
		 * @return the alternative fallback value, or null if no alternative exists
		 */
		default Object getAlternativeValue() {
			return fromNumber(1);
		}
	}

	private static final Map<Class<?>, TypeParser> PARSERS = new HashMap<>();

	/**
	 * TypeParser for Enum types parsed by name (for string columns).
	 * <p>
	 * 按枚举名称解析的 TypeParser（用于字符串列）。
	 */
	private static final class EnumByNameParser implements TypeParser {
		private final Class<? extends Enum<?>> enumClass;

		@SuppressWarnings("unchecked")
		EnumByNameParser(Class<?> enumType) {
			this.enumClass = (Class<? extends Enum<?>>) enumType;
		}

		@SuppressWarnings({ "unchecked", "rawtypes" })
		@Override
		public Object parse(String value) {
			if (value == null || value.isEmpty()) {
				return null;
			}
			try {
				return Enum.valueOf((Class) enumClass, value);
			} catch (IllegalArgumentException e) {
				log.debug("Cannot parse enum {} from name '{}'", enumClass.getSimpleName(), value);
				return null;
			}
		}

		@Override
		public Object fromNumber(Number num) {
			// String column should not receive numeric values
			log.debug("EnumByNameParser received numeric value {} for enum {}", num, enumClass.getSimpleName());
			return null;
		}

		@Override
		public Object getZeroValue() {
			Enum<?>[] constants = enumClass.getEnumConstants();
			return (constants != null && constants.length > 0) ? constants[0] : null;
		}

		@Override
		public Object getAlternativeValue() {
			Enum<?>[] constants = enumClass.getEnumConstants();
			return (constants != null && constants.length > 1) ? constants[1] : null;
		}
	}

	/**
	 * TypeParser for Enum types parsed by ordinal (for numeric columns).
	 * <p>
	 * 按枚举序号解析的 TypeParser（用于数字列）。
	 */
	private static final class EnumByOrdinalParser implements TypeParser {
		private final Class<? extends Enum<?>> enumClass;

		@SuppressWarnings("unchecked")
		EnumByOrdinalParser(Class<?> enumType) {
			this.enumClass = (Class<? extends Enum<?>>) enumType;
		}

		@Override
		public Object parse(String value) {
			if (value == null || value.isEmpty()) {
				return null;
			}
			try {
				int ordinal = Integer.parseInt(value);
				return fromNumber(ordinal);
			} catch (NumberFormatException e) {
				log.debug("Cannot parse enum {} from numeric value '{}'", enumClass.getSimpleName(), value);
				return null;
			}
		}

		@Override
		public Object fromNumber(Number num) {
			if (num == null) {
				return null;
			}
			int ordinal = num.intValue();
			Enum<?>[] constants = enumClass.getEnumConstants();
			if (ordinal >= 0 && ordinal < constants.length) {
				return constants[ordinal];
			}
			log.debug("Ordinal {} out of range for enum {} (size: {})", 
					ordinal, enumClass.getSimpleName(), constants.length);
			return null;
		}

		@Override
		public Object getZeroValue() {
			Enum<?>[] constants = enumClass.getEnumConstants();
			return (constants != null && constants.length > 0) ? constants[0] : null;
		}

		@Override
		public Object getAlternativeValue() {
			Enum<?>[] constants = enumClass.getEnumConstants();
			return (constants != null && constants.length > 1) ? constants[1] : null;
		}
	}

	/**
	 * TypeParser for CodeEnum types parsed by code (for numeric columns).
	 * <p>
	 * 按 CodeEnum.getCode() 解析的 TypeParser（用于数字列）。
	 */
	private static final class EnumByCodeParser implements TypeParser {
		private final Class<? extends Enum<?>> enumClass;

		@SuppressWarnings("unchecked")
		EnumByCodeParser(Class<?> enumType) {
			this.enumClass = (Class<? extends Enum<?>>) enumType;
		}

		@Override
		public Object parse(String value) {
			if (value == null || value.isEmpty()) {
				return null;
			}
			try {
				int code = Integer.parseInt(value);
				return fromNumber(code);
			} catch (NumberFormatException e) {
				log.debug("Cannot parse enum {} from numeric value '{}'", enumClass.getSimpleName(), value);
				return null;
			}
		}

		@Override
		public Object fromNumber(Number num) {
			if (num == null) {
				return null;
			}
			int code = num.intValue();
			Enum<?>[] constants = enumClass.getEnumConstants();
			for (Enum<?> constant : constants) {
				if (((com.github.xuse.querydsl.types.CodeEnum<?>) constant).getCode() == code) {
					return constant;
				}
			}
			log.debug("Cannot find enum {} with code {}", enumClass.getSimpleName(), code);
			return null;
		}

		@Override
		public Object getZeroValue() {
			Enum<?>[] constants = enumClass.getEnumConstants();
			return (constants != null && constants.length > 0) ? constants[0] : null;
		}

		@Override
		public Object getAlternativeValue() {
			Enum<?>[] constants = enumClass.getEnumConstants();
			return (constants != null && constants.length > 1) ? constants[1] : null;
		}
	}

	static {
		TypeParser stringParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return value;
			}
			@Override
			public Object fromNumber(Number num) {
				return num.toString();
			}
			@Override
			public Object getZeroValue() {
				return "";  // Empty string for AGGRESSIVE_DEFAULT strategy
			}
			@Override
			public Object getAlternativeValue() {
				return " ";  // Single space as alternative when empty string is unsaved
			}
		};
		TypeParser intParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return Integer.parseInt(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return num.intValue();
			}
		};
		TypeParser longParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return Long.parseLong(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return num.longValue();
			}
		};
		TypeParser shortParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return Short.parseShort(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return num.shortValue();
			}
		};
		TypeParser byteParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return Byte.parseByte(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return num.byteValue();
			}
		};
		TypeParser floatParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return Float.parseFloat(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return num.floatValue();
			}
		};
		TypeParser doubleParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return Double.parseDouble(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return num.doubleValue();
			}
		};
		TypeParser bigDecimalParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return new java.math.BigDecimal(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return new java.math.BigDecimal(num.toString());
			}
		};
		TypeParser bigIntegerParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return new java.math.BigInteger(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return java.math.BigInteger.valueOf(num.longValue());
			}
		};
		TypeParser booleanParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				if ("true".equalsIgnoreCase(value) || "1".equals(value)) {
					return Boolean.TRUE;
				}
				if ("false".equalsIgnoreCase(value) || "0".equals(value)) {
					return Boolean.FALSE;
				}
				return null;
			}
			@Override
			public Object fromNumber(Number num) {
				return num.intValue() != 0;
			}
		};
		TypeParser sqlDateParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return java.sql.Date.valueOf(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for date types
			}
		};
		TypeParser sqlTimeParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return java.sql.Time.valueOf(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for time types
			}
		};
		TypeParser sqlTimestampParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return java.sql.Timestamp.valueOf(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for timestamp types
			}
		};
		TypeParser utilDateParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				try {
					return new java.util.Date(java.sql.Timestamp.valueOf(value).getTime());
				} catch (IllegalArgumentException e) {
					return new java.util.Date(java.sql.Date.valueOf(value).getTime());
				}
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for date types
			}
		};
		TypeParser localDateParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return java.time.LocalDate.parse(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for date types
			}
		};
		TypeParser localTimeParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return java.time.LocalTime.parse(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for time types
			}
		};
		TypeParser localDateTimeParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				// Try with 'T' separator first (ISO format), then with space (SQL format)
				if (value.contains("T")) {
					return java.time.LocalDateTime.parse(value);
				}
				return java.time.LocalDateTime.parse(value.replace(' ', 'T'));
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for datetime types
			}
		};
		TypeParser instantParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				// Try parsing as ISO instant, or convert from timestamp string
				try {
					return java.time.Instant.parse(value);
				} catch (java.time.format.DateTimeParseException e) {
					// Try as SQL timestamp and convert to Instant
					return java.sql.Timestamp.valueOf(value).toInstant();
				}
			}
			@Override
			public Object fromNumber(Number num) {
				// Treat number as epoch milliseconds
				return java.time.Instant.ofEpochMilli(num.longValue());
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for instant types
			}
		};
		TypeParser offsetDateTimeParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return java.time.OffsetDateTime.parse(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for datetime types
			}
		};
		TypeParser zonedDateTimeParser = new TypeParser() {
			@Override
			public Object parse(String value) {
				return java.time.ZonedDateTime.parse(value);
			}
			@Override
			public Object fromNumber(Number num) {
				return null;
			}
			@Override
			public Object getAlternativeValue() {
				return null;  // No reasonable alternative for datetime types
			}
		};

		PARSERS.put(String.class, stringParser);
		PARSERS.put(int.class, intParser);
		PARSERS.put(Integer.class, intParser);
		PARSERS.put(long.class, longParser);
		PARSERS.put(Long.class, longParser);
		PARSERS.put(short.class, shortParser);
		PARSERS.put(Short.class, shortParser);
		PARSERS.put(byte.class, byteParser);
		PARSERS.put(Byte.class, byteParser);
		PARSERS.put(float.class, floatParser);
		PARSERS.put(Float.class, floatParser);
		PARSERS.put(double.class, doubleParser);
		PARSERS.put(Double.class, doubleParser);
		PARSERS.put(java.math.BigDecimal.class, bigDecimalParser);
		PARSERS.put(java.math.BigInteger.class, bigIntegerParser);
		PARSERS.put(boolean.class, booleanParser);
		PARSERS.put(Boolean.class, booleanParser);
		PARSERS.put(java.sql.Date.class, sqlDateParser);
		PARSERS.put(java.sql.Time.class, sqlTimeParser);
		PARSERS.put(java.sql.Timestamp.class, sqlTimestampParser);
		PARSERS.put(java.util.Date.class, utilDateParser);
		PARSERS.put(java.time.LocalDate.class, localDateParser);
		PARSERS.put(java.time.LocalTime.class, localTimeParser);
		PARSERS.put(java.time.LocalDateTime.class, localDateTimeParser);
		PARSERS.put(java.time.Instant.class, instantParser);
		PARSERS.put(java.time.OffsetDateTime.class, offsetDateTimeParser);
		PARSERS.put(java.time.ZonedDateTime.class, zonedDateTimeParser);
	}

	/**
	 * Pre-compute null substitution values for each column in the given path list.
	 * <p>
	 * For each column that is NOT NULL and has a parseable default value expression,
	 * the corresponding array position will contain the Java literal to use as a substitute.
	 * Positions for nullable columns or columns without parseable defaults will be null.
	 * <p>
	 * <b>Note:</b> This method is kept for backward compatibility and testing.
	 * In production code, {@link #applySubstitutions} directly accesses PathMapping cache.
	 *
	 * @param entity the relational path (table metadata)
	 * @param paths  the ordered list of column paths participating in the batch SQL
	 * @return an array of substitution values (same length as paths), or null if no substitution is needed
	 */
	static Object[] computeNullSubstitutions(RelationalPath<?> entity, List<Path<?>> paths) {
		RelationalPathEx<?> pathEx = RelationalPathExImpl.toRelationPathEx(entity);
		if (pathEx == null) {
			return null;
		}
		log.debug("Computing null substitutions for {} columns", paths.size());
		Object[] substitutions = null;
		int len = paths.size();
		for (int i = 0; i < len; i++) {
			Path<?> p = paths.get(i);
			log.debug("Column {}: {} (type: {})", i, p.getMetadata().getName(), p.getType().getSimpleName());
			ColumnMapping mapping = pathEx.getColumnMetadata(p);
			if (mapping == null) {
				// constantPath may contain Path instances different from entity's registered paths.
				// Try lookup by field name as fallback.
				Path<?> entityPath = pathEx.getColumn(p.getMetadata().getName());
				if (entityPath != null) {
					mapping = pathEx.getColumnMetadata(entityPath);
				}
				if (mapping == null) {
					throw new IllegalStateException("No column mapping found for path: " + p 
							+ " (class=" + p.getClass().getName() + ", name=" + p.getMetadata().getName() + ")");
				}
			}
			// Get the cached null substitution from PathMapping
			Object javaValue = mapping.getNullSubstitution();
			if (javaValue != null) {
				if (substitutions == null) {
					substitutions = new Object[len];
				}
				substitutions[i] = javaValue;
				log.debug("  -> Substitution value: {} (type: {})", javaValue, javaValue.getClass().getSimpleName());
			} else {
				log.debug("  -> No substitution needed");
			}
		}
		return substitutions;
	}

	/**
	 * Apply null substitutions to a values array extracted from a bean.
	 * For each position where the value is null or unsaved and a substitution exists, replace with the substitution.
	 *
	 * @param entity        the relational path (table metadata) - needed to check unsaved values
	 * @param paths         the ordered list of column paths
	 * @param values        the values array from beanCodec.values(bean)
	 * @param substitutions the pre-computed substitution array (may be null)
	 */
	/**
	 * Apply null substitutions to a values array extracted from a bean.
	 * For each position where the value is null or unsaved, get substitution from PathMapping.
	 * If strategy is AGGRESSIVE_DEFAULT, also provide fallback values for NOT NULL columns without default expressions.
	 *
	 * @param entity   the relational path (table metadata) - needed to check unsaved values
	 * @param paths    the ordered list of column paths
	 * @param values   the values array from beanCodec.values(bean)
	 * @param strategy the batch null strategy
	 */
	/**
	 * Apply null substitutions to a values array extracted from a bean.
	 * For each position where the value is null or unsaved, get substitution from PathMapping.
	 * If strategy is AGGRESSIVE, also provide fallback values for NOT NULL columns without default expressions.
	 * <p>
	 * <b>Note:</b> If strategy is {@code null}, this method does nothing (SAFE mode - use addBatch path).
	 *
	 * @param entity   the relational path (table metadata) - needed to check unsaved values
	 * @param paths    the ordered list of column paths
	 * @param values   the values array from beanCodec.values(bean)
	 * @param strategy the batch null strategy, or null for SAFE mode
	 */
	static void applySubstitutions(RelationalPath<?> entity, List<Path<?>> paths, Object[] values,
			com.github.xuse.querydsl.config.BatchNullStrategy strategy) {
		// If strategy is null, use SAFE mode (addBatch path) - no substitution needed
		if (strategy == null) {
			return;
		}
		
		RelationalPathEx<?> pathEx = RelationalPathExImpl.toRelationPathEx(entity);
		if (pathEx == null) {
			return;
		}
		int len = Math.min(values.length, paths.size());
		for (int i = 0; i < len; i++) {
			Path<?> p = paths.get(i);
			ColumnMapping mapping = pathEx.getColumnMetadata(p);
			if (mapping == null) {
				Path<?> entityPath = pathEx.getColumn(p.getMetadata().getName());
				if (entityPath != null) {
					mapping = pathEx.getColumnMetadata(entityPath);
				}
			}
			if (mapping == null) {
				continue;
			}
			
			// Determine which strategy to use based on column nullability
			com.github.xuse.querydsl.config.BatchNullStrategy.ColumnStrategy columnStrategy = 
					mapping.isNullable() ? strategy.getNullableStrategy() : strategy.getNotNullStrategy();
			
			// Skip if strategy is SKIP
			if (columnStrategy == com.github.xuse.querydsl.config.BatchNullStrategy.ColumnStrategy.SKIP) {
				continue;
			}
			
			// Check if value is null or unsaved
			// Note: We intentionally do NOT check for com.querydsl.sql.types.Null here.
			// Null.CONSTANT is explicit user intent to insert SQL NULL, should not be substituted.
			boolean shouldSubstitute = values[i] == Null.DEFAULT || values[i] == null || mapping.isUnsavedValue(values[i]);
			
			if (shouldSubstitute) {
				Object substitution = null;
				
				// First, try to get substitution from PathMapping (from defaultExpression)
				// These are user-configured defaults and should always be used
				substitution = mapping.getNullSubstitution();
				
				// If no substitution and strategy is AGGRESSIVE, provide fallback value
				// Note: For nullable columns, AGGRESSIVE behaves the same as USE_DEFAULT (no aggressive fallback)
				if (substitution == null && columnStrategy == com.github.xuse.querydsl.config.BatchNullStrategy.ColumnStrategy.AGGRESSIVE) {
					if (!mapping.isNullable() && mapping.getGenerated() == null && mapping.getCustomType() == null) {
						substitution = getAggressiveFallbackValue(mapping);
						if (substitution != null) {
							log.debug("Applying aggressive fallback at position {}: {} (type: {})", i, substitution, substitution.getClass().getSimpleName());
						}
					}
				}
				
				if (substitution != null) {
					log.debug("Substituting value {} at position {} with: {}", values[i], i, substitution);
					values[i] = substitution;
				}
			}
		}
	}

	/**
	 * Get aggressive fallback value for a Java type when no default expression is defined.
	 * Returns null for types that don't have a sensible zero/empty value.
	 * <p>
	 * If the zero value (0, false, "") would be treated as unsaved, tries to use an alternative value (1, true, " ").
	 * <p>
	 * 为没有定义默认值表达式的 Java 类型获取激进的兜底值。
	 * 对于没有合理零值/空值的类型返回 null。
	 * 如果零值（0、false、""）会被视为未保存值，则尝试使用替代值（1、true、" "）。
	 */
	private static Object getAggressiveFallbackValue(ColumnMapping mapping) {
		Class<?> javaType = mapping.getType();
		int jdbcType = mapping.getJdbcType();
		TypeParser parser = getTypeParser(javaType, jdbcType);
		if (parser != null) {
			// Try zero value first
			Object zeroValue = parser.getZeroValue();
			// Check if the zero value would be treated as "unsaved"
			// If so, try the alternative value
			if (zeroValue != null && mapping.isUnsavedValue(zeroValue)) {
				log.debug("Zero value {} would be treated as unsaved for column {}, trying alternative value", 
						zeroValue, mapping.fieldName());
				zeroValue = parser.getAlternativeValue();
			}
			// No usable alternative
			return mapping.isUnsavedValue(zeroValue) ? null : zeroValue;
		}
		// Unknown type
		return null;
	}

	/**
	 * Get the TypeParser for the given Java type.
	 * Supports standard types from PARSERS map and Enum types.
	 * <p>
	 * For Enum types:
	 * <ul>
	 *   <li>If jdbcType is string-based (VARCHAR, CHAR, etc.), parse by enum name</li>
	 *   <li>If jdbcType is numeric and enum implements {@link com.github.xuse.querydsl.types.CodeEnum}, parse by code</li>
	 *   <li>Otherwise, parse by ordinal</li>
	 * </ul>
	 * <p>
	 * 获取给定 Java 类型的 TypeParser。
	 * 支持 PARSERS 映射中的标准类型和枚举类型。
	 * <p>
	 * 对于枚举类型：
	 * <ul>
	 *   <li>如果 jdbcType 是字符串类型（VARCHAR、CHAR 等），按枚举名称解析</li>
	 *   <li>如果 jdbcType 是数字类型且枚举实现了 {@link com.github.xuse.querydsl.types.CodeEnum}，按 code 解析</li>
	 *   <li>否则，按 ordinal 解析</li>
	 * </ul>
	 *
	 * @param javaType the target Java type (required)
	 * @param jdbcType the JDBC type code (from java.sql.Types), required for Enum parsing strategy
	 * @return the TypeParser, or null if the type is not supported
	 */
	private static TypeParser getTypeParser(Class<?> javaType, int jdbcType) {
		// First check standard parsers
		TypeParser parser = PARSERS.get(javaType);
		if (parser != null) {
			return parser;
		}

		// Handle Enum types
		if (javaType != null && javaType.isEnum()) {
			return createEnumParser(javaType, jdbcType);
		}

		return null;
	}

	/**
	 * Create a TypeParser for Enum types based on the JDBC type.
	 * Returns one of three predefined parser strategies.
	 * <p>
	 * 为枚举类型创建 TypeParser，根据 JDBC 类型决定解析策略。
	 * 返回三种预定义解析策略之一。
	 *
	 * @param enumType the enum class
	 * @param jdbcType the JDBC type code
	 * @return a TypeParser for the enum type
	 */
	private static TypeParser createEnumParser(Class<?> enumType, int jdbcType) {
		boolean isStringType = com.github.xuse.querydsl.sql.support.SQLTypeUtils.isChars(jdbcType);
		
		if (isStringType) {
			// String column: parse by enum name
			return new EnumByNameParser(enumType);
		} else {
			// Numeric column: parse by code or ordinal
			boolean isCodeEnum = com.github.xuse.querydsl.types.CodeEnum.class.isAssignableFrom(enumType);
			if (isCodeEnum) {
				return new EnumByCodeParser(enumType);
			} else {
				return new EnumByOrdinalParser(enumType);
			}
		}
	}

	/**
	 * Attempt to parse a default expression into a Java literal value.
	 * Returns null for complex expressions (CURRENT_TIMESTAMP, UUID(), function calls, etc.)
	 * <p>
	 * Package-private for testing.
	 */
	public static Object parseDefaultToJavaValue(Expression<?> defaultExpr, int jdbcType, Class<?> javaType, String fieldName) {
		// Primary path: TemplateExpression (from @ColumnSpec(defaultValue="...") or defaultExpression(String))
		if (defaultExpr instanceof TemplateExpression) {
			Template t = ((TemplateExpression<?>) defaultExpr).getTemplate();
			if (t == null) {
				return null;
			}
			String template = t.toString();
			if (template == null || template.isEmpty()) {
				return null;
			}
			// Skip known SQL function expressions
			String upper = template.toUpperCase();
			if (upper.contains("CURRENT_TIMESTAMP") || upper.contains("NOW()")
					|| upper.contains("UUID") || upper.contains("(")) {
				return null;
			}
			try {
				return doParseValue(template, javaType, jdbcType);
			} catch (Exception e) {
				log.debug("Cannot parse default value '{}' for field '{}' to Java literal, skipping auto-substitution.",
						template, fieldName);
				return null;
			}
		}
		// Secondary path: Constant (from defaultValue(0), defaultValue("text"), defaultValueInString(...))
		if (defaultExpr instanceof com.querydsl.core.types.Constant) {
			Object constant = ((com.querydsl.core.types.Constant<?>) defaultExpr).getConstant();
			return convertConstant(constant, javaType, jdbcType);
		}
		// Unknown expression type — cannot parse
		return null;
	}

	/**
	 * Convert a Constant value to match the target Java type.
	 * For example, defaultValue(1) produces Integer(1), but if the field is Long, we need Long(1).
	 * 
	 * @param constant the constant value to convert
	 * @param javaType the target Java type
	 * @param jdbcType the JDBC type code (from java.sql.Types)
	 * @return the converted value, or null if conversion is not possible
	 */
	private static Object convertConstant(Object constant, Class<?> javaType, int jdbcType) {
		if (constant == null) {
			return null;
		}
		if (javaType == null || javaType.isInstance(constant)) {
			return constant;
		}
		if (constant instanceof Number) {
			TypeParser parser = getTypeParser(javaType, jdbcType);
			return parser != null ? parser.fromNumber((Number) constant) : constant;
		}
		if (constant instanceof Boolean) {
			if (javaType == Boolean.class || javaType == boolean.class) {
				return constant;
			}
			TypeParser parser = getTypeParser(javaType, jdbcType);
			return parser != null ? parser.fromNumber(((Boolean) constant) ? 1 : 0) : null;
		}
		if (constant instanceof String) {
			String str = ((String) constant).trim();
			TypeParser parser = getTypeParser(javaType, jdbcType);
			if (parser != null) {
				try {
					return parser.parse(str);
				} catch (Exception e) {
					return null;
				}
			}
			// If no parser found and target is String, return as-is
			return javaType == String.class ? constant : null;
		}
		return null;
	}

	/**
	 * Parse a SQL default value template string into a Java object of the target type.
	 * Uses the registered {@link TypeParser} strategy for the given javaType.
	 */
	private static Object doParseValue(String template, Class<?> javaType, int jdbcType) {
		// Handle quoted string literals: 'xxx' or ''
		if (template.startsWith("'") && template.endsWith("'")) {
			String inner = template.substring(1, template.length() - 1);
			// Unescape SQL single-quote escaping: '' → '
			inner = inner.replace("''", "'");
			TypeParser parser = getTypeParser(javaType, jdbcType);
			if (parser != null) {
				return parser.parse(inner.trim());
			}
			// If no parser found and target is String, return the unescaped string
			return javaType == String.class ? inner : null;
		}
		// Unquoted value — lookup parser by Java type
		TypeParser parser = getTypeParser(javaType, jdbcType);
		if (parser != null) {
			return parser.parse(template.trim());
		}
		// Unknown target type — try numeric fallback
		if (com.github.xuse.querydsl.util.StringUtils.isNumericString(template)) {
			if (template.contains(".")) {
				return Double.parseDouble(template.trim());
			}
			long val = Long.parseLong(template.trim());
			return (val >= Integer.MIN_VALUE && val <= Integer.MAX_VALUE) ? (int) val : val;
		}
		return null;
	}
}
