/*
 * Copyright 2015, The Querydsl Team (http://www.querydsl.com/team)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.xuse.querydsl.sql.dml;

import static com.github.xuse.querydsl.sql.expression.AbstractMapperSupport.SCENARIO_INSERT;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

import com.github.xuse.querydsl.config.BatchNullStrategy;
import com.github.xuse.querydsl.config.BatchNullStrategy.ColumnStrategy;
import com.github.xuse.querydsl.config.ConfigurationEx;
import com.github.xuse.querydsl.lambda.LambdaColumn;
import com.github.xuse.querydsl.sql.Mappers;
import com.github.xuse.querydsl.sql.RelationalPathEx;
import com.github.xuse.querydsl.sql.RelationalPathExImpl;
import com.github.xuse.querydsl.sql.SQLBindingsAlter;
import com.github.xuse.querydsl.sql.column.ColumnMapping;
import com.github.xuse.querydsl.sql.ddl.DDLExpressions;
import com.github.xuse.querydsl.sql.dialect.SpecialFeature;
import com.github.xuse.querydsl.sql.expression.AbstractMapperSupport;
import com.github.xuse.querydsl.sql.expression.AdvancedMapper;
import com.github.xuse.querydsl.sql.expression.BeanCodec;
import com.github.xuse.querydsl.sql.expression.BeanCodecManager;
import com.github.xuse.querydsl.sql.expression.BindingProvider.ListPathBindings;
import com.github.xuse.querydsl.sql.expression.ConverterWrappedBean;
import com.github.xuse.querydsl.sql.expression.ValueExtractor;
import com.github.xuse.querydsl.sql.log.ContextKeyConstants;
import com.github.xuse.querydsl.sql.log.ExceptionLogDetail;
import com.github.xuse.querydsl.sql.routing.RoutingStrategy;
import com.github.xuse.querydsl.sql.support.SQLTypeUtils;
import com.github.xuse.querydsl.util.Exceptions;
import com.querydsl.core.QueryFlag.Position;
import com.querydsl.core.QueryMetadata;
import com.querydsl.core.Tuple;
import com.querydsl.core.types.ConstantImpl;
import com.querydsl.core.types.Expression;
import com.querydsl.core.types.ParamExpression;
import com.querydsl.core.types.ParamNotSetException;
import com.querydsl.core.types.Path;
import com.querydsl.core.util.CollectionUtils;
import com.querydsl.core.util.ResultSetAdapter;
import com.querydsl.sql.ColumnMetadata;
import com.querydsl.sql.Configuration;
import com.querydsl.sql.RelationalPath;
import com.querydsl.sql.SQLBindings;
import com.querydsl.sql.SQLListenerContextImpl;
import com.querydsl.sql.SQLQuery;
import com.querydsl.sql.SQLSerializer;
import com.querydsl.sql.SQLSerializerAlter;
import com.querydsl.sql.dml.AbstractSQLInsertClause;
import com.querydsl.sql.dml.Mapper;
import com.querydsl.sql.dml.SQLInsertBatch;
import com.querydsl.sql.types.Null;

import lombok.extern.slf4j.Slf4j;

/**
 * SQLInsertClause defines an INSERT INTO clause If you need to subtype this,
 * use {@link AbstractSQLInsertClause} instead.
 *
 * @author tiwe. revised by Joey
 */
@Slf4j
public class SQLInsertClauseAlter extends AbstractSQLInsertClause<SQLInsertClauseAlter> {
	private static final BatchNullStrategy NOT_SET =BatchNullStrategy.of(ColumnStrategy.SKIP, ColumnStrategy.SKIP);

	private final ConfigurationEx configuration;

	private RoutingStrategy routing;

	private ExceptionLogDetail exceptionLogDetail;

	private Boolean writeNulls;
	
	/**
	 * Per-clause override for batch null strategy. If set, takes precedence over global config.
	 * - null: not set (use global config)
	 * - SAFE_ADDBACH: explicitly set to SAFE mode
	 * - other: use the specified strategy
	 */
	private com.github.xuse.querydsl.config.BatchNullStrategy overrideBatchNullStrategy = NOT_SET;

	/**
	 * Whether to automatically populate @AutoGenerated columns during execute.
	 * Only applies to the set() path (single-row insert without populate/batch).
	 */
	private boolean writeAutoColumns = true;

	/**
	 * 旧Batch模式专用。
	 * 
	 * In a Batch scenario, parameter normalization (with unspecified columns filled
	 * with NULL) is performed starting from the second row to ensure consistency
	 * with the parameters of the first row. Ultimately, ensure that the Batch
	 * operation consists of a single statement with multiple sets of parameters.
	 * 
	 * 在Batch情况下，对第二条开始的数据进行参数归一化（未指定列补NULL），确保与第一条记录的参数一致。最终确保Batch操作仅有一条语句多组参数。
	 */
	private boolean normalizeBatchValues = true;

	private transient Collection<Object> populatedBatch = Collections.emptyList();

	@SuppressWarnings("rawtypes")
	private transient Mapper batchMapper;

	SQLInsertClauseAlter(Connection connection, ConfigurationEx configuration, RelationalPath<?> entity,
			SQLQuery<?> subQuery) {
		super(connection, configuration.get(), entity, subQuery);
		this.configuration = configuration;
		this.batchToBulk = configuration.getTemplates().isBatchToBulkInDefault();
	}

	SQLInsertClauseAlter(Connection connection, ConfigurationEx configuration, RelationalPath<?> entity) {
		super(connection, configuration.get(), entity);
		this.configuration = configuration;
		this.batchToBulk = configuration.getTemplates().isBatchToBulkInDefault();
	}

	public SQLInsertClauseAlter(Supplier<Connection> connection, ConfigurationEx configuration,
			RelationalPath<?> entity, SQLQuery<?> subQuery) {
		super(connection, configuration.get(), entity, subQuery);
		this.configuration = configuration;
		this.batchToBulk = configuration.getTemplates().isBatchToBulkInDefault();
	}

	public SQLInsertClauseAlter(Supplier<Connection> connection, ConfigurationEx configuration,
			RelationalPath<?> entity) {
		super(connection, configuration.get(), entity);
		this.configuration = configuration;
		this.batchToBulk = configuration.getTemplates().isBatchToBulkInDefault();
	}

	/**
	 * Add fields with automatically generated values.
	 * <p>
	 * 添加自动生成值的字段。仅当使用SET方法逐个设置字段时有用。
	 * <p>
	 * Note: since {@code writeAutoColumns} defaults to {@code true}, this method
	 * is now called automatically during {@code execute()} for single-row inserts.
	 * Use {@link #writeAutoColumns(boolean)} to control this behavior instead.
	 * 
	 * @return SQLInsertClauseAlter
	 */
	private SQLInsertClauseAlter populateAutoGeneratedColumns() {
		RelationalPathEx<?> entity = (RelationalPathEx<?>) this.entity;
		List<Path<?>> paths = entity.getColumns();
		for (Path<?> p : paths) {
			ColumnMapping metadata = entity.getColumnMetadata(p);
			// 用户没有显式设置过值时才会填充字段
			if (metadata.getGenerated() == null) {
				continue;
			}
			if (columns.contains(p)) {
				continue;
			}
			Object value = AdvancedMapper.asAutoValue(metadata.getGenerated(), metadata, SCENARIO_INSERT);
			if (value instanceof Expression<?>) {
				columns.add(p);
				values.add((Expression<?>) value);
			} else if (!metadata.isUnsavedValue(value)) {
				columns.add(p);
				assert value != null;
				values.add(ConstantImpl.create(value));
			}
		}
		return this;
	}

	/**
	 * Execute the clause and return the generated keys as a ResultSet
	 * <p>
	 * 执行该子句并将生成的键作为 ResultSet 返回。
	 * 
	 * @return result set with generated keys
	 */
	public ResultSet executeWithKeys() {
		context = startContext(connection(), metadata, entity);
		boolean returned = false; // 是否已把连接生命周期移交给返回的 ResultSet
		try {
			mergeDifferentBatchMode();
			PreparedStatement stmt;
			if (!populatedBatch.isEmpty()) {
				// 新Batch模式
				if (batchToBulk) {
					stmt = newStatementBulk(populatedBatch, true);
					executeStatementInternal(stmt,false);
				} else {
					stmt = newStatementBatch(populatedBatch, true);
					executeBatchInternal(Collections.singletonList(stmt), false);
				}
			}else if (batches.isEmpty()) {
				//单条模式
				if (writeAutoColumns) {
					populateAutoGeneratedColumns();
				}
				stmt = createStatement(true);
				listeners.notifyInsert(entity, metadata, columns, values, subQuery);
				executeStatementInternal(stmt,false);
			} else {
				//旧Bath模式 
				if (batchToBulk) {
					stmt = createStatement(true);
					listeners.notifyInserts(entity, metadata, batches);
					listeners.preExecute(context);
					executeStatementInternal(stmt,false);
				} else {
					Collection<PreparedStatement> stmts = createStatements(true);
					if (stmts.size() > 1) {
						throw new IllegalStateException(
								"executeWithKeys called with batch statement and multiple SQL strings");
					}
					stmt = stmts.iterator().next();
					listeners.notifyInserts(entity, metadata, batches);
					executeBatchInternal(Collections.singletonList(stmt), false);
				}	
			}
			final Statement stmt2 = stmt;
			ResultSet rs = stmt.getGeneratedKeys();
			ResultSetAdapter result = new ResultSetAdapter(rs) {
				@Override
				public void close(){
					SQLTypeUtils.close(rs);
					SQLTypeUtils.close(stmt2);
					reset();
					endContext(context);
				}
			};
			returned = true; // 交接成功，finally 不再关闭
			return result;
		} catch (RuntimeException e) {
			onException(context, e);
			throw e;
		} catch (SQLException e) {
			onException(context, e);
			throw configuration.translate(queryString, constants, e);
		}finally {
			if(!returned) {
				reset();
				endContext(context);	
			}
		}
	}

	@Override
	public long execute() {
		context = startContext(connection(), metadata, entity);
		try {
			mergeDifferentBatchMode();
			if (!populatedBatch.isEmpty()) {
				if (batchToBulk) {
					//新模式:基于拼装长SQL
					PreparedStatement stmt = newStatementBulk(populatedBatch, false);
					return executeStatementInternal(stmt,true);
				} else {
					//新模式:基于JDBC Batch
					PreparedStatement stmt = newStatementBatch(populatedBatch, false);
					return executeBatchInternal(Collections.singleton(stmt),true);
				}
			} else if (batches.isEmpty()) {
				// 单条模式
				if (writeAutoColumns) {
					populateAutoGeneratedColumns();
				}
				if (columns.isEmpty()) {
					return 0;// 没有任何数据需要插入
				}
				PreparedStatement stmt = createStatement(false);
				listeners.notifyInsert(entity, metadata, columns, values, subQuery);
				return executeStatementInternal(stmt,true);
			} else {
				//旧Batch模式
				if (batchToBulk) {
					//旧Batch模式：批量语句拼接模式
					PreparedStatement stmt = createStatement(false);
					listeners.notifyInserts(entity, metadata, batches);
					return executeStatementInternal(stmt,true);
				} else {
					// JDBC批操作模式
					Collection<PreparedStatement> stmts = createStatements(false);
					listeners.notifyInserts(entity, metadata, batches);
					return executeBatchInternal(stmts,true);
				}	
			}
		} catch (RuntimeException e) {
			onException(context, e);
			throw e;
		} catch (SQLException e) {
			onException(context, e);
			throw configuration.translate(queryString, constants, e);
		} finally {
			reset();
			endContext(context);
		}
	}

	private long executeStatementInternal(PreparedStatement stmt, boolean close) throws SQLException {
		try {
			listeners.preExecute(context);
			long start = System.currentTimeMillis();
			int rc = stmt.executeUpdate();
			postExecuted(context, System.currentTimeMillis() - start, "Insert", rc);
			return rc;
		}finally {
			if(close) {
				SQLTypeUtils.close(stmt);
			}
		}
	}

	private long executeBatchInternal(Collection<PreparedStatement> stmts, boolean close) throws SQLException{
		listeners.preExecute(context);
		long start = System.currentTimeMillis();
		try {
			int rc = 0;
			for (PreparedStatement stmt : stmts) {
				for (int i : stmt.executeBatch()) {
					rc += i;	
				}
			}
			postExecuted(context, System.currentTimeMillis() - start, "BatchInsert", rc);
			return rc;
		} finally {
			if(close) {
				stmts.forEach(SQLTypeUtils::close);
			}
		}
	}
	
	@Override
    public SQLInsertClauseAlter addBatch() {
        if (subQueryBuilder != null) {
            subQuery = subQueryBuilder.select(values.toArray(new Expression[0])).clone();
            values.clear();
        }
        if(batches.isEmpty()) {
        	batches.add(new SQLInsertBatch(columns, values, subQuery));
		} else if (normalizeBatchValues) {
        	List<Path<?>> columns = this.columns;
			List<Path<?>> template = batches.get(0).getColumns();
        	List<Expression<?>> batchValues=this.values;
        	if(!fastEquals(template,columns)) {
				batchValues = normalizeValues(template, columns, batchValues);
    		}
        	batches.add(new SQLInsertBatch(template, batchValues, subQuery));
        }else {
        	batches.add(new SQLInsertBatch(columns, values, subQuery));
        }
        this.columns.clear();
        this.values.clear();
        subQuery = null;
        return this;
    }

	private boolean fastEquals(List<Path<?>> template, List<Path<?>> columns) {
		int len = template.size();
		if(len!=columns.size()) {
			return false;
		}
		for(int i=0;i<len;i++) {
			//use !=, not !equals()
			if(template.get(i)!=columns.get(i)) {
				return false;
			}
		}
		return true;
	}

	private List<Expression<?>> normalizeValues(List<Path<?>> template, List<Path<?>> columns, List<Expression<?>> values) {
		Map<Path<?>, Expression<?>> valuesMap = new HashMap<>();
		for (int i = 0; i < columns.size(); i++) {
			valuesMap.put(columns.get(i), values.get(i));
		}
		int len = template.size();
		List<Expression<?>> result = new ArrayList<>(len);
		for (int i = 0; i < len; i++) {
			Path<?> p = template.get(i);
			Expression<?> value = valuesMap.get(p);
			if (value == null) {
				value = configuration.getTemplates().getDefaultExpr();
			}
			if (value == null) {
				value = Null.CONSTANT;
			}
			result.add(value);
		}
		return result;
	}

	private PreparedStatement newStatementBulk(Collection<Object> beans, boolean withKeys) throws SQLException {
		// 一遍扫描确定 SQL 列序并生成多组 values，SQL+参数注入 context（prePrepare 打印日志，
		// 否则 SQL 语法有误时来不及打印就抛出异常）
		BulkProcessor bulk = new BulkProcessor(beans);
		listeners.prePrepare(context);
		bulk.prepare(withKeys);
		listeners.prepared(context);
		return bulk.stmt;
	}

	private PreparedStatement newStatementBatch(Collection<Object> beans, boolean withKeys) throws SQLException {
		Iterator<Object> iter = beans.iterator();
		Object bean = iter.next();
		
		//收集参数，SQL+参数注入context，prepare打印日志（否则SQL语法有误时没来得及打印就抛出异常了）
		BatchProcessor batch = createBatch(bean);
		List<Object[]> values = batch.collectBatchValues(iter, beans.size() - 1);
		listeners.prePrepare(context);
		
		//生成Statement
		batch.prepareBatchStatement(withKeys,values);
		listeners.prepared(context);
		return batch.stmt;
	}
	
	/*
	 * 父类方法不支持routing参数。
	 */
	@Override
	protected SQLSerializerAlter createSerializer() {
		SQLSerializerAlter serializer = new SQLSerializerAlter(configuration, true, false, true);
		serializer.setUseLiterals(useLiterals);
		serializer.setRouting(routing);
		return serializer;
	}

	/**
	 * Set the data for bulk insertion
	 * <p>
	 * 设置要批量插入的数据
	 *
	 * @implSpec 使用带NULLBinding的方式设置变量，批量装配时，无论是否为null值，都会在SQL中显示声明，因此数据库的默认值将无效
	 * @param beans data to insert
	 * @return this SQLInsertClauseAlter
	 */
	public SQLInsertClauseAlter populateBatch(Collection<?> beans) {
		//退化：走旧Batch路径
		if (getEffectiveBatchNullStrategy() == null) {
			return populateBatchViaAddBatch(beans);
		}
		int type = Mappers.TYPE_BEAN;
		if(writeNulls==null || writeNulls) {
			type = type | Mappers.NULLS_BIND;
		}
		populateBatch0(wrapCollectionIfNeeded(beans), Mappers.get(SCENARIO_INSERT, type));
		return this;
	}

	/**
	 * Fallback path: use the traditional addBatch() approach for each bean.
	 * Each bean is processed through the full Mapper pipeline individually,
	 * so null values on NOT NULL columns are simply omitted from the SQL,
	 * letting the database DEFAULT take effect naturally.
	 * <p>
	 * 安全路径：使用传统的addBatch()方式逐条处理。每条记录独立通过Mapper处理，
	 * null值的NOT NULL字段不会出现在SQL中，数据库DEFAULT自然生效。
	 */
	@SuppressWarnings({ "rawtypes", "unchecked" })
	private SQLInsertClauseAlter populateBatchViaAddBatch(Collection<?> beans) {
		if (beans.isEmpty()) {
			return this;
		}
		// Disable normalization so each bean keeps its own column set.
		// Different beans may produce different SQL statements (grouped and executed separately).
		this.normalizeBatchValues = false;
		Mapper mapper = Mappers.get(SCENARIO_INSERT, Mappers.TYPE_BEAN);
		for (Object bean : beans) {
			Object target = wrapIfNeeded(bean);
			Map<Path<?>, Object> values = mapper.createMap(entity, target);
			for (Map.Entry<Path<?>, Object> entry : values.entrySet()) {
				set((Path) entry.getKey(), entry.getValue());
			}
			addBatch();
		}
		return this;
	}

	/**
	 * Set the data for bulk insertion
	 * <p>
	 * 设置要批量插入的数据
	 *
	 * @param beans  data to insert
	 * @param mapper the mapper object.
	 * @return this SQLInsertClauseAlter
	 * @see AdvancedMapper
	 * @param <T> The type of target object.
	 */
	public <T> SQLInsertClauseAlter populateBatch(Collection<T> beans, Mapper<?> mapper) {
		if (mapper == null) {
			return populateBatch(beans);
		}
		populateBatch0(beans, mapper);
		return this;
	}

	/**
	 * Set the data for bulk insertion (Tuple objects)
	 * <p>
	 * 设置要批量插入的动态数据（用Tuple类型表示）
	 * 
	 * @param beans 数据
	 * @return this
	 */
	public SQLInsertClauseAlter populateTuples(Collection<Tuple> beans) {
		populateBatch0(beans, Mappers.get(SCENARIO_INSERT,Mappers.NULLS_BIND | Mappers.TYPE_TUPLE));
		return this;
	}

	private void populateBatch0(Collection<?> beans, @SuppressWarnings("rawtypes") Mapper mapper) {
		if (beans.isEmpty()) {
			return;
		}
		Collection<Object> batch;
		if ((batch = populatedBatch).isEmpty()) {
			batch = populatedBatch = new ArrayList<>();
		}
		batch.addAll(beans);
		this.batchMapper = mapper;
	}

	/**
	 * {@inheritDoc}
	 */
	@SuppressWarnings("unchecked")
	public SQLInsertClauseAlter populate(Object bean) {
		int type = Mappers.TYPE_BEAN;
		if (writeNulls!=null && writeNulls) {
			type = type | Mappers.NULLS_BIND;
		}
		Object target = wrapIfNeeded(bean);
		populate(target, Mappers.get(SCENARIO_INSERT, type));
		// Mapper with SCENARIO_INSERT already handles @AutoGenerated columns,
		// skip redundant populateAutoGeneratedColumns() during execute().
		this.writeAutoColumns = false;
		return this;
	}

	/**
	 * Populate the INSERT clause with the properties of the given bean.
	 * The properties need to match the fields of the clause's entity instance.
	 * <p>
	 * 使用给定 bean 的属性填充 INSERT 子句。这些属性需要与子句的实体实例的字段匹配。
	 * 
	 * @param bean bean to use for population
	 * @return the current object
	 */
	@SuppressWarnings("unchecked")
	public SQLInsertClauseAlter populate(Tuple bean) {
		int type = Mappers.TYPE_TUPLE;
		if (writeNulls !=null && writeNulls) {
			type = type | Mappers.NULLS_BIND;
		}
		populate(bean, Mappers.get(SCENARIO_INSERT,type));
		// Mapper with SCENARIO_INSERT already handles @AutoGenerated columns,
		// skip redundant populateAutoGeneratedColumns() during execute().
		this.writeAutoColumns = false;
		return this;
	}

	private Object wrapIfNeeded(Object bean) {
		return ConverterWrappedBean.wrapIfNeeded(bean, entity);
	}

	/**
	 * Wrap a collection of beans if needed. Checks the first element to determine
	 * if wrapping is required (all elements are the same type).
	 */
	private Collection<?> wrapCollectionIfNeeded(Collection<?> beans) {
		if (beans.isEmpty()) {
			return beans;
		}
		Object first = beans.iterator().next();
		if (entity.getType().isInstance(first)) {
			return beans;
		}
		List<ConverterWrappedBean> wrapped = new ArrayList<>(beans.size());
		for (Object bean : beans) {
			wrapped.add(ConverterWrappedBean.of(bean));
		}
		return wrapped;
	}
	
	
    /**
     * Set whether batches should be optimized into a single bulk operation.
     * Will revert to batches, if bulk is not supported.
     * 
     * 
     */
    public SQLInsertClauseAlter batchToBulk(boolean b) {
        this.batchToBulk = b && configuration.getTemplates().isBatchToBulkSupported();
        return this;
    }

	/**
	 * Set whether to automatically populate @AutoGenerated columns during execute.
	 * Defaults to {@code true}. Only affects the set() path (single-row insert).
	 * <p>
	 * 设置是否在execute时自动填充 @AutoGenerated 标注的列。默认为true。
	 * 仅对使用set()方法逐列设置的单条插入生效。
	 *
	 * @param flag true to auto-populate, false to skip
	 * @return this
	 */
	public SQLInsertClauseAlter writeAutoColumns(boolean flag) {
		this.writeAutoColumns = flag;
		return this;
	}

	protected Collection<PreparedStatement> createStatements(boolean withKeys) throws SQLException {
		boolean addBatches = !super.configuration.getUseLiterals();
		listeners.preRender(context);
		if (subQueryBuilder != null) {
			subQuery = subQueryBuilder.select(values.toArray(new Expression[0])).clone();
			values.clear();
		}
		Map<String, PreparedStatement> stmts = new HashMap<>();
		// add first batch
		{
			SQLSerializerAlter serializer = createSerializer();
			SQLInsertBatch batch = batches.get(0);
			serializer.serializeInsert(metadata, entity, batch.getColumns(), batch.getValues(), batch.getSubQuery());
			String sql = serializer.toString();
			PreparedStatement stmt = prepareStatementAndSetParameters(
					new SQLBindingsAlter(sql, serializer.getConstants(), serializer.getConstantPaths()), withKeys);
			if (addBatches) {
				stmt.addBatch();
			}
			stmts.put(sql, stmt);
			context.addSQL(createBindings(metadata, serializer));
			listeners.rendered(context);
		}
		// add other batches
		int maxLoginBatch = configuration.getMaxRecordsLogInBatch();
		for (int i = 1; i < batches.size(); i++) {
			SQLInsertBatch batch = batches.get(i);
			listeners.preRender(context);
			SQLSerializerAlter serializer = createSerializer(); 
			serializer.serializeInsert(metadata, entity, batch.getColumns(), batch.getValues(), batch.getSubQuery());
			String sql = serializer.toString();
			if (i <= maxLoginBatch) {
				context.addSQL(createBindings(metadata, serializer));
				listeners.rendered(context);
			}
			PreparedStatement stmt = stmts.get(serializer.toString());
			if (stmt == null) {
				stmt = prepareStatementAndSetParameters(
						new SQLBindingsAlter(sql, serializer.getConstants(), serializer.getConstantPaths()), withKeys);
				stmts.put(serializer.toString(), stmt);
			} else {
				setParameters(stmt, serializer.getConstants(), serializer.getConstantPaths(), metadata.getParams());
			}
			if (addBatches) {
				stmt.addBatch();
			}
		}
		if (stmts.size() > 1) {
			log.warn("There are multi sqls in this batch.{}", stmts.keySet());
		}
		return stmts.values();
	}
	
	//仅单条模式和旧Batch+Bulk模式进入该方法
	private SQLBindingsAlter getSQLForSingle() {
		SQLSerializerAlter serializer = createSerializer(); 
		if (subQueryBuilder != null) {
			subQuery = subQueryBuilder.select(values.toArray(new Expression[values.size()])).clone();
			values.clear();
		}
		if (!batches.isEmpty() && batchToBulk) {
			//旧Batch Bulk路径
			serializer.serializeInsert(metadata, entity, batches);
		} else {
			//非Batch插入，默认原生实现
			serializer.serializeInsert(metadata, entity, columns, values, subQuery);
		}
		return createBindings(metadata, serializer);
	}
	
	@Override
	public List<SQLBindings> getSQL() {
		if (batches.isEmpty()) {
			//单条模式
			return Collections.singletonList(getSQLForSingle());
        } else if (batchToBulk) {
        	//旧Batch+Bulk模式
            SQLSerializer serializer = createSerializer();
            serializer.serializeInsert(metadata, entity, batches);
            return Collections.singletonList(createBindings(metadata, serializer));
        } else {
            List<SQLBindings> builder = new ArrayList<>();
            for (SQLInsertBatch batch : batches) {
                SQLSerializer serializer = createSerializer();
                serializer.serializeInsert(metadata, entity, batch.getColumns(), batch.getValues(), batch.getSubQuery());
                builder.add(createBindings(metadata, serializer));
            }
            return CollectionUtils.unmodifiableList(builder);
        }
	}

	public <B,T extends Comparable<?>> SQLInsertClauseAlter set(LambdaColumn<B,T> path, T value) {
		return super.set(path, value);
	}
	
	public <B,T extends Comparable<?>> SQLInsertClauseAlter set(LambdaColumn<B,T> path, Expression<T> value) {
		return super.set(path, value);
	}
	
	//仅单条+旧Batch+Bulk模式进入
	protected PreparedStatement createStatement(boolean withKeys) throws SQLException {
		listeners.preRender(context);
		SQLBindingsAlter bindings=getSQLForSingle();
		context.addSQL(bindings);
		listeners.rendered(context);
		return prepareStatementAndSetParameters(bindings, withKeys);
	}

	protected PreparedStatement prepareStatementAndSetParameters(SQLBindingsAlter bindings, boolean withKeys)
			throws SQLException {
		listeners.prePrepare(context);
		this.queryString = bindings.getSQL();
		this.constants = bindings.getNullFriendlyBindings();
		PreparedStatement stmt;
		if (withKeys) {
			if (entity.getPrimaryKey() != null && !configuration.has(SpecialFeature.PREFER_AUTOGENERATED_KEYS)) {
				String[] target = new String[entity.getPrimaryKey().getLocalColumns().size()];
				for (int i = 0; i < target.length; i++) {
					Path<?> path = entity.getPrimaryKey().getLocalColumns().get(i);
					String column = ColumnMetadata.getName(path);
					column = configuration.getColumnOverride(entity.getSchemaAndTable(), column);
					target[i] = column;
				}
				stmt = connection().prepareStatement(queryString, target);
			} else {
				stmt = connection().prepareStatement(queryString, Statement.RETURN_GENERATED_KEYS);
			}
		} else {
			stmt = connection().prepareStatement(queryString);
		}
		setParameters(stmt, constants, bindings.getPaths(), metadata.getParams());
		context.addPreparedStatement(stmt);
		listeners.prepared(context);
		return stmt;
	}

	protected void setParameters(PreparedStatement stmt, List<?> objects, List<Path<?>> constantPaths,
			Map<ParamExpression<?>, ?> params) {
		if (objects.size() != constantPaths.size()) {
			throw new IllegalArgumentException(
					"Expected " + objects.size() + " paths, " + "but got " + constantPaths.size());
		}
		for (int i = 0; i < objects.size(); i++) {
			Object o = objects.get(i);
			try {
				if (o instanceof ParamExpression) {
					if (!params.containsKey(o)) {
						throw new ParamNotSetException((ParamExpression<?>) o);
					}
					o = params.get(o);
				}
				super.configuration.set(stmt, constantPaths.get(i), i + 1, o);
			} catch (SQLException e) {
				// 本方法 override querydsl 父类 AbstractSQLClause.setParameters，父类签名不抛受检异常，
				// 因此不得不就地 translate 为 RuntimeException（规范：受父类约束的方法允许转换）。
				// 注意：此处只转换、不 onException，上报由最外层 execute/executeWithKeys 统一负责一次。
				Path<?> p = constantPaths == null ? null : constantPaths.get(i);
				log.error(queryString + "\nField " + i + " path=" + p + " set error. " + e.getMessage());
				throw super.configuration.translate(e);
			}
		}
	}

	@Override
	protected SQLBindingsAlter createBindings(QueryMetadata metadata, SQLSerializer serializer) {
		String queryString = serializer.toString();
		List<Object> args = new ArrayList<>();
		Map<ParamExpression<?>, Object> params = metadata.getParams();
		for (Object o : serializer.getConstants()) {
			if (o instanceof ParamExpression) {
				if (!params.containsKey(o)) {
					throw new ParamNotSetException((ParamExpression<?>) o);
				}
				o = metadata.getParams().get(o);
			}
			args.add(o);
		}
		return new SQLBindingsAlter(queryString, args, serializer.getConstantPaths());
	}

	private void postExecuted(SQLListenerContextImpl context, long cost, String action, long count) {
		context.setData(ContextKeyConstants.ELAPSED_TIME, cost);
		context.setData(ContextKeyConstants.COUNT, count);
		context.setData(ContextKeyConstants.ACTION, action);
		if (this.configuration.getSlowSqlWarnMillis() <= cost) {
			context.setData(ContextKeyConstants.IMPORTANT, ContextKeyConstants.SLOW);
		}
		listeners.executed(context);
	}

	/**
	 * Set how much detail is logged if this statement fails.
	 * <p>设置本语句执行失败时的异常日志详细度。适用于预期内的异常（如主键冲突用于流程控制），
	 * 避免完整堆栈淹没业务日志，同时不影响其它语句的错误日志。
	 *
	 * @param detail {@link ExceptionLogDetail#FULL_STACK} 完整堆栈（默认）、
	 *        {@link ExceptionLogDetail#BRIEF} 仅SQL和异常摘要、
	 *        {@link ExceptionLogDetail#NONE} 不打印
	 * @return this
	 */
	public SQLInsertClauseAlter exceptionLog(ExceptionLogDetail detail) {
		this.exceptionLogDetail = detail;
		return this;
	}

	@Override
	protected void onException(SQLListenerContextImpl context, Exception e) {
		if (this.exceptionLogDetail != null) {
			context.setData(ContextKeyConstants.EXCEPTION_LOG_DETAIL, this.exceptionLogDetail);
		}
		super.onException(context, e);
	}

	public SQLInsertClauseAlter withRouting(RoutingStrategy routing) {
		this.routing = routing;
		return this;
	}

	/**
	 * By default, null values in the bean will not write to the database. After
	 * call this method, the population method such as {@link #populate(Object)}
	 * will allow the system to attempt to update null values to the database.
	 *
	 * <h2>中文</h2> 默认不会写入Bean中null数值。开启后会尝试更新null值到数据库中。
	 * 
	 * @param flag true to enable the update null values feature.
	 * @return SQLUpdateClauseAlter
	 */
	public SQLInsertClauseAlter writeNulls(boolean flag) {
		if (!columns.isEmpty()) {
			throw Exceptions.illegalState("This method should be called before method 'populate'.");
		}
		this.writeNulls = flag;
		return this;
	}

	// 将缓存的批量对象，按旧模式写入到batches中。
	@SuppressWarnings({ "rawtypes", "unchecked" })
	private void mergeDifferentBatchMode() {
		if (batches.isEmpty() || populatedBatch.isEmpty()) {
			return;
		}
		Mapper mapper = batchMapper;
		for (Object obj : populatedBatch) {
			Map<Path<?>, Object> values = mapper.createMap(entity, obj);
			for (Map.Entry<Path<?>, Object> entry : values.entrySet()) {
				set((Path) entry.getKey(), entry.getValue());
			}
			addBatch();
		}
		populatedBatch = null;
	}

	/**
	 * Bulk 写入实现：将整批对象拼装为单条 {@code INSERT INTO t (cols) VALUES (...),(...),...} 语句，一次执行。
	 * <p>
	 * 与 {@link BatchProcessor}（一条 SQL + JDBC 多组参数）不同，Bulk 是一条 SQL 内含多组 VALUES。
	 * 采用一遍扫描算法确定固定的 SQL 列序（有效列并集），随后逐组生成 values（无效单元格写 {@code DEFAULT} 关键字），
	 * 因此各组绑定变量数量可不同（{@code ?} 与 {@code DEFAULT} 混排）。
	 * <p>
	 * 三列序：实体列序（{@code entity.getColumns()}）→ SQL 列序（有效列并集）→ 绑定列序（序列化产出的 constantPaths）。
	 */
	final class BulkProcessor {

		private final SQLBindingsAlter principle;

		/** 绑定列序：整条 bulk SQL 中所有 {@code ?} 对应的列（多组累积，可变长）。 */
		private final List<Path<?>> bindingPaths;

		/** 每组绑定值，与 {@link #bindingPaths} 顺序一一对应。 */
		private final List<Object> bindingVariables;

		private PreparedStatement stmt;

		BulkProcessor(Collection<Object> beans) {
			useLiterals = false;
			RelationalPathEx<?> pathEx = RelationalPathExImpl.toRelationPathEx(entity);
			List<Path<?>> allCols = pathEx.getColumns();
			int m = allCols.size();
			ColumnMapping[] metaColumns = new ColumnMapping[m];
			for (int i = 0; i < m; i++) {
				metaColumns[i] = pathEx.getColumnMetadata(allCols.get(i));
			}
			boolean writeNullsMode = (writeNulls != null && writeNulls);

			// —— 第一遍（唯一遍历对象）：抽值 + 求有效列并集 + 缓存原始值 ——
			Object firstBean = beans.iterator().next();
			// 包装 DTO 用 extractValues（按实体列序，未映射列为 NOT_AVAILABLE）；普通 bean 用全局共享 codec。
			BeanCodec codec = (firstBean instanceof ConverterWrappedBean) ? null
					: AdvancedMapper.getBeanCodec(pathEx, firstBean);
			List<Object[]> rows = new ArrayList<>(beans.size()); //所有对象的列值数组 
			boolean[] effective = new boolean[m];//列值有效记录 
			for (Object bean : beans) {
				Object[] raw = extractRaw(codec, pathEx, bean);
				rows.add(raw);
				for (int i = 0; i < m; i++) {
					if (metaColumns[i].isNotInsert() || isKeyAutoIncrement(metaColumns[i])) {
						continue;
					}
					Object v = raw[i];
					if (v == ConverterWrappedBean.NOT_AVAILABLE) {
						continue; // DTO 未映射该列 → 不纳入有效列（缺失单元格后续补 DEFAULT）
					}
					if (writeNullsMode) {
						effective[i] = true; // 写 NULL 模式：所有可插入列都进 SQL 列序
					} else if (metaColumns[i].getGenerated() != null
							|| !AbstractMapperSupport.isUnsavedValue(metaColumns[i], v)) {
						effective[i] = true; // 有 @AutoGenerated 或值有效 → 纳入有效列
					}
				}
			}

			// —— 固定 SQL 列序（有效列并集，保持实体列序） ——
			List<Path<?>> effectColumns = new ArrayList<>();
			int[] sqlColIdx = new int[m];
			int sqlColCount = 0;
			for (int i = 0; i < m; i++) {
				if (effective[i]) {
					effectColumns.add(allCols.get(i));
					sqlColIdx[sqlColCount++] = i;
				}
			}

			// —— 第二遍：并行遍历 beans 与 rows（同顺序同索引），按 SQL 列序生成每组 values，处理 auto 值与写回 ——
			int maxLoginBatch = configuration.getMaxRecordsLogInBatch();
			List<List<Expression<?>>> valueGroups = new ArrayList<>(rows.size());
			this.bindingVariables = new ArrayList<>();
			List<SQLBindingsAlter> logBindings = new ArrayList<>();
			Iterator<Object> beanIter = beans.iterator();
			int r = 0;
			for (Object[] raw : rows) {
				Object bean = beanIter.next(); // beans 与 rows 由第一遍按同一顺序构建，天然对齐
				List<Object> groupBindValues = new ArrayList<>(sqlColCount);
				List<Expression<?>> group = buildValueGroup(raw, bean, metaColumns, sqlColIdx,
						sqlColCount, effectColumns, writeNullsMode, groupBindValues);
				this.bindingVariables.addAll(groupBindValues);
				valueGroups.add(group);
				if (r++ < maxLoginBatch) {
					logBindings.add(new SQLBindingsAlter(null, new ArrayList<>(groupBindValues), effectColumns));
				}
			}

			// —— 序列化：单条 bulk SQL + 尾部 flags ——
			SQLSerializerAlter serializer = createSerializer();
			listeners.preRender(context);
			serializer.serializeForInsertBulk(metadata, entity, effectColumns, valueGroups);
			if (!metadata.getFlags().isEmpty()) {
				serializer.serialize(Position.END, metadata.getFlags());
			}
			this.principle = new SQLBindingsAlter(serializer.toString(), serializer.getConstants(),
					serializer.getConstantPaths());
			this.bindingPaths = serializer.getConstantPaths();
			// 尾部 flags（如 on duplicate key update set gender=?, content=concat(...)）可能引入额外的绑定常量，
			// 这些常量位于序列化产出的 constants 尾部、不在各组 VALUES 中，需要补进 bindingValues 才能正确 set。
			List<?> allConstants = serializer.getConstants();
			for (int i = bindingVariables.size(); i < allConstants.size(); i++) {
				bindingVariables.add(allConstants.get(i));
			}
			// principle（含真实 SQL）必须先入 context，日志格式化取首条的 SQL；随后追加各组展示用绑定。
			context.addSQL(principle);
			for (SQLBindingsAlter lb : logBindings) {
				context.addSQL(lb);
			}
			listeners.rendered(context);
		}

		PreparedStatement prepare(boolean withKeys) throws SQLException {
			this.stmt = createBulkStatement(principle.getSQL(), withKeys);
			List<Path<?>> paths = this.bindingPaths;
			Configuration cfg = configuration.get();
			int len = bindingVariables.size();
			for (int i = 0; i < len;) {
				Path<?> path = paths.get(i);
				Object o = bindingVariables.get(i);
				try {
					cfg.set(stmt, path, ++i, o);
				} catch (SQLException e) {
					log.error(principle.getSQL() + "\nField " + (i - 1) + " path=" + path + " set error. "
							+ e.getMessage());
					throw e;
				}
			}
			return stmt;
		}

		private PreparedStatement createBulkStatement(String sql, boolean withKeys) throws SQLException {
			PreparedStatement stmt;
			if (withKeys) {
				if (entity.getPrimaryKey() != null && !configuration.has(SpecialFeature.PREFER_AUTOGENERATED_KEYS)) {
					String[] target = new String[entity.getPrimaryKey().getLocalColumns().size()];
					for (int i = 0; i < target.length; i++) {
						Path<?> path = entity.getPrimaryKey().getLocalColumns().get(i);
						String column = ColumnMetadata.getName(path);
						column = configuration.getColumnOverride(entity.getSchemaAndTable(), column);
						target[i] = column;
					}
					stmt = connection().prepareStatement(sql, target);
				} else {
					stmt = connection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
				}
			} else {
				stmt = connection().prepareStatement(sql);
			}
			context.addPreparedStatement(stmt);
			return stmt;
		}

		/**
		 * 按固定 SQL 列序为单条记录生成一组 value 表达式。绑定值收集到 {@code groupBindValues}，
		 * 并对该组做防御性空值兜底（{@link #applyGroupSubstitutions}）。
		 *
		 * @param raw             该记录按实体列序抽取的原始值
		 * @param bean            原始对象（用于 @AutoGenerated 回写）
		 * @param metaColumns            实体列的 ColumnMapping（按实体列序）
		 * @param sqlColIdx       SQL 列在实体列序中的下标映射
		 * @param sqlColCount     SQL 列数
		 * @param columns         固定 SQL 列序
		 * @param writeNullsMode  writeNulls==true 时无效值写 NULL，否则写 DEFAULT 关键字
		 * @param groupBindValues 出参：本组的绑定值（与 group 中的 {@code ?} 一一对应）
		 * @return 本组的 value 表达式列表
		 */
		private List<Expression<?>> buildValueGroup(Object[] raw, Object bean, ColumnMapping[] metaColumns, int[] sqlColIdx,
				int sqlColCount, List<Path<?>> columns, boolean writeNullsMode, List<Object> groupBindValues) {
			List<Expression<?>> group = new ArrayList<>(sqlColCount);
			for (int k = 0; k < sqlColCount; k++) {
				int i = sqlColIdx[k];
				buildCell(metaColumns[i], raw[i], bean, writeNullsMode, group, groupBindValues);
			}
			// 防御层：对本组绑定值中的 null/unsaved 用 defaultExpression 兜底（穿透 DEFAULT 关键字）
			if (!groupBindValues.isEmpty()) {
				applyGroupSubstitutions(group, groupBindValues, columns);
			}
			return group;
		}

		/**
		 * 为单个列生成一个 value 单元：处理 @AutoGenerated（含回写）、无效值（写 DEFAULT 关键字或 NULL）、
		 * 内联表达式、常量绑定四种情况。结果追加到 {@code group}，若为绑定值则同时追加到 {@code groupBindValues}。
		 */
		private void buildCell(ColumnMapping cm, Object rawValue, Object bean, boolean writeNullsMode,
				List<Expression<?>> group, List<Object> groupBindValues) {
			Object v = rawValue;
			// DTO 未映射的列（NOT_AVAILABLE）等同无效 → 该单元格补 DEFAULT
			boolean unsaved = (v == ConverterWrappedBean.NOT_AVAILABLE)
					|| AbstractMapperSupport.isUnsavedValue(cm, v);
			if (v == ConverterWrappedBean.NOT_AVAILABLE) {
				v = null;
			}
			// @AutoGenerated：解析并按需回写（与 AdvancedMapper 共用逻辑，回写由 writeback 内部处理表达式值）
			Object autoV = AbstractMapperSupport.resolveAutoGenerated(cm, unsaved, SCENARIO_INSERT, bean);
			if (autoV != AbstractMapperSupport.NO_AUTO_VALUE) {
				v = autoV;
				unsaved = false;
			}
			if (unsaved) {
				if (writeNullsMode) {
					group.add(Null.CONSTANT); // 写 NULL（下方 applySubstitutions 可能兜底）
					groupBindValues.add(Null.DEFAULT);
				} else {
					group.add(DDLExpressions.defaultExpr()); // 无效 → DEFAULT 关键字（内联，不占绑定）
				}
			} else if (v instanceof Expression) {
				group.add((Expression<?>) v); // 内联表达式（currentTimestamp 等），不占绑定
			} else {
				group.add(ConstantImpl.create(v)); // 绑定 ?
				groupBindValues.add(v);
			}
		}
	}

	private static Object[] extractRaw(BeanCodec codec, RelationalPathEx<?> pathEx, Object bean) {
		if (bean instanceof ConverterWrappedBean) {
			return ((ConverterWrappedBean) bean).extractValues(pathEx);
		}
		if (codec != null && pathEx.getType().isInstance(bean)) {
			return codec.values(bean);
		}
		return AdvancedMapper.getBeanCodec(pathEx, bean).values(bean);
	}

	private static boolean isKeyAutoIncrement(ColumnMapping cm) {
		return cm.isAutoIncrement();
	}

	/**
	 * 对一组绑定值应用 {@link DefaultValueHelper#applySubstitutions} 防御兜底。
	 * group 中位于 {@code DEFAULT} 关键字或内联表达式的单元格不参与（它们不在 bindValues 中）。
	 * bindValues 与 group 中"绑定列"（{@link ConstantImpl} 或 {@link Null#CONSTANT}）一一对应。
	 */
	private void applyGroupSubstitutions(List<Expression<?>> group, List<Object> bindValues, List<Path<?>> columns) {
		List<Path<?>> bindCols = new ArrayList<>(bindValues.size());
		for (int c = 0; c < group.size(); c++) {
			Expression<?> e = group.get(c);
			if (e instanceof ConstantImpl || e == Null.CONSTANT) {
				bindCols.add(columns.get(c));
			}
		}
		if (bindCols.size() != bindValues.size()) {
			return; // 对齐异常时跳过防御兜底，避免错位
		}
		Object[] arr = bindValues.toArray();
		DefaultValueHelper.applySubstitutions(entity, bindCols, arr, getEffectiveBatchNullStrategy());
		for (int i = 0; i < arr.length; i++) {
			bindValues.set(i, arr[i]);
		}
	}
	
	/**
	 * 批量写入的优化实现。针对单一对象大批量写入，在MySQL进行性能测试。发现
	 * -- JDBC驱动的Batch性能很差，远不如MyBatis直接多组values(?),(?)拼接的速度 (194,262ms VS 10,984ms)
	 * -- 改用setBatchToBulk(true)进行测试，发现queryDSL为每个对象生成SQL再分组，也不快(16,999ms vs 7538ms)。
	 * -- 用下列方法实现后， 达到(2876ms vs 7538ms)
	 */
	final class BatchProcessor {
		private final SQLBindingsAlter principle;
		
		private final List<Path<?>> columnPaths;
		
		private final List<Path<?>> bingingPaths;
		
		private final ValueExtractor valueExtractor;

		private PreparedStatement stmt;
		
		private final int maxLoginBatch = configuration.getMaxRecordsLogInBatch();
		
		private int count = 0;

		BatchProcessor(List<Path<?>> columns,List<Expression<?>> firstValues, Object firstBean) {
			useLiterals=false;
			this.columnPaths = columns;
			SQLSerializerAlter serializer = createSerializer(); 
			listeners.preRender(context);
			serializer.serializeForInsert(metadata, entity, columns, firstValues, null);
			
			//添加定制后缀。如on duplicate update set
			if (!metadata.getFlags().isEmpty()) {
				serializer.serialize(Position.END, metadata.getFlags());
	        }
			
			principle = new SQLBindingsAlter(serializer.toString(), serializer.getConstants(),
					serializer.getConstantPaths());
			this.bingingPaths = serializer.getConstantPaths();
			if (firstBean instanceof ConverterWrappedBean) {
				this.valueExtractor = ((ConverterWrappedBean) firstBean)
						.toValueExtractor((RelationalPathEx<?>) entity, bingingPaths);
			} else {
				this.valueExtractor = BeanCodecManager.getInstance()
						.getCodec(firstBean.getClass(), new ListPathBindings(bingingPaths));
			}
			context.addSQL(principle);
			listeners.rendered(context);
		}

		private List<Object[]> collectBatchValues(Iterator<Object> iter,int len) {
			List<Object[]> result = new ArrayList<>(len);
			while(iter.hasNext()) {
				Object bean = iter.next();
				if (valueExtractor.isInstance(bean)) {
					Object[] values = this.valueExtractor.values(bean);
					DefaultValueHelper.applySubstitutions(entity, bingingPaths, values, getEffectiveBatchNullStrategy());
					if (count++ < maxLoginBatch) {
						//输入到日志用与展示的批次，仅展示部分。
						context.addSQL(new SQLBindingsAlter(null, Arrays.asList(values), bingingPaths));
					}
					result.add(values);
				} else {
					throw Exceptions.illegalArgument("Object in batch must be in consistent type {}. encounter a {}",
							valueExtractor.getType(), bean.getClass());
				}				
			}
			return result;
		}
		
		public void prepareBatchStatement(boolean withKeys,List<Object[]> values) throws SQLException {
			SQLBindingsAlter first = this.principle;
			List<Object> bindings = first.getNullFriendlyBindings();
			Object[] arr = bindings.toArray();
			DefaultValueHelper.applySubstitutions(entity, bingingPaths, arr, getEffectiveBatchNullStrategy());
			bindings = java.util.Arrays.asList(arr);
			this.stmt = createStatement(first.getSQL(), withKeys);
			
			//设置第一组绑定参数
			setParameters(stmt, bindings, first.getPaths(), null);
			stmt.addBatch();
			
			//针对每组值，设置绑定值。Batch模式是一句SQL对应多组参数，因此参数必须完全匹配一致。
			Configuration cfg = configuration.get();
			for (Object[] vs:values) { 
				addBatchParams(vs, cfg);
			}
		}
	
		private void addBatchParams(Object[] values, Configuration config) throws SQLException {
			List<Path<?>> paths = this.bingingPaths;
			PreparedStatement stmt = this.stmt;
			int len = values.length;
			for (int i = 0; i < len;) {
				Path<?> path = paths.get(i);
				Object o = values[i];
				try {
					config.set(stmt, path, ++i, o);
				} catch (SQLException e) {
					log.error(principle.getSQL() + "\nField " + (i - 1) + " path=" + path + " set error. "
							+ e.getMessage());
					throw e;
				}
			}
			stmt.addBatch();
		}
	
		private PreparedStatement createStatement(String sql, boolean withKeys) throws SQLException {
			PreparedStatement stmt;
			if (withKeys) {
				if (entity.getPrimaryKey() != null && !configuration.has(SpecialFeature.PREFER_AUTOGENERATED_KEYS)) {
					String[] target = new String[entity.getPrimaryKey().getLocalColumns().size()];
					for (int i = 0; i < target.length; i++) {
						Path<?> path = entity.getPrimaryKey().getLocalColumns().get(i);
						String column = ColumnMetadata.getName(path);
						column = configuration.getColumnOverride(entity.getSchemaAndTable(), column);
						target[i] = column;
					}
					stmt = connection().prepareStatement(sql, target);
				} else {
					stmt = connection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
				}
			} else {
				stmt = connection().prepareStatement(sql);
			}
			context.addPreparedStatement(stmt);
			return stmt;
		}
	}
	/*
	 *  在Batch操作中，有三个PathList的概念，需要区分清楚（以下简称三列序）
	 *  <li>Full Path（实体列序，实体的所有列）: Entity的全部列。RelationalPath.getColumns()得到这个列表</li>
	 *  <li>SQL Path（SQL列序，出现在Column中）: 参与到SQL中的列，在SQL Batch中的是是这个列表</li>
	 *  <li>Constant Path（绑定列序）: 即每条数据需要传入的列,在SQLSerializer.getConstantPath()得到这个列表</li>
	 */
	private BatchProcessor createBatch(Object obj) {
		List<Path<?>> columns = new ArrayList<>();
		List<Expression<?>> values = new ArrayList<>();
		@SuppressWarnings("unchecked")
		//这个Map决定了SQL列序
		Map<Path<?>, Object> map = batchMapper.createMap(entity, obj);
		for (Map.Entry<Path<?>, Object> entry : map.entrySet()) {
			Path<?> p = entry.getKey();
			columns.add(p);
			Object value = entry.getValue();
			if (value instanceof Expression<?>) {
				values.add((Expression<?>) value);
			} else if (value != null) {
				values.add(ConstantImpl.create(value));
			} else {
				values.add(Null.CONSTANT);
			}
		}
		return new BatchProcessor(columns, values, obj);
	}
	
	public SQLInsertClauseAlter normalizeBatch(boolean flag) {
		this.normalizeBatchValues = flag;
		return this;
	}

	/**
	 * Override the batch null strategy for this specific insert clause.
	 * This takes precedence over the global {@link ConfigurationEx#getBatchNullStrategy()}.
	 * <p>
	 * <b>Special values:</b>
	 * <ul>
	 * <li>{@code null} - Use SAFE mode (traditional addBatch path, null columns omitted from SQL)</li>
	 * <li>{@link BatchNullStrategy#AUTO_DEFAULT} - Use defaultExpression for NOT NULL columns</li>
	 * <li>{@link BatchNullStrategy#AGGRESSIVE_DEFAULT} - Provide fallback values even without defaultExpression</li>
	 * <li>Custom strategy - Use {@link BatchNullStrategy#of} or {@code withXxxStrategy()} methods</li>
	 * </ul>
	 * <p>
	 * <h2>中文</h2>
	 * 为当前插入语句覆盖批量null值处理策略，优先于全局配置。
	 * <p>
	 * <b>特殊值：</b>
	 * <ul>
	 * <li>{@code null} - 使用安全模式（传统 addBatch 路径，null 列从 SQL 中省略）</li>
	 * <li>{@link BatchNullStrategy#AUTO_DEFAULT} - 对 NOT NULL 列使用 defaultExpression</li>
	 * <li>{@link BatchNullStrategy#AGGRESSIVE_DEFAULT} - 即使没有 defaultExpression 也提供兜底值</li>
	 * <li>自定义策略 - 使用 {@link BatchNullStrategy#of} 或 {@code withXxxStrategy()} 方法</li>
	 * </ul>
	 *
	 * @param strategy the strategy to use for this batch insert, or null for SAFE mode
	 * @return this SQLInsertClauseAlter
	 * @see com.github.xuse.querydsl.config.BatchNullStrategy
	 */
	public SQLInsertClauseAlter batchNullStrategy(com.github.xuse.querydsl.config.BatchNullStrategy strategy) {
		this.overrideBatchNullStrategy = strategy;
		return this;
	}

	private com.github.xuse.querydsl.config.BatchNullStrategy getEffectiveBatchNullStrategy() {
		if (overrideBatchNullStrategy == NOT_SET) {
			return configuration.getBatchNullStrategy();
		}
		return overrideBatchNullStrategy;
	}
}
