package com.github.xuse.querydsl.sql.dml;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.github.xuse.querydsl.entity.Foo;
import com.github.xuse.querydsl.lambda.LambdaTable;
import com.github.xuse.querydsl.repository.CRUDRepository;
import com.github.xuse.querydsl.sql.integration.db.AbstractTestBase;

/**
 * Integration test verifying that AUTO_DEFAULT strategy correctly handles null values
 * for NOT NULL columns with default values during batch insert.
 * <p>
 * Uses the Foo entity which has:
 * <ul>
 *   <li>{@code code}: VARCHAR(64) NOT NULL DEFAULT '' — the core scenario being tested</li>
 *   <li>{@code codeType}: INT NOT NULL DEFAULT 1 — numeric default</li>
 *   <li>{@code version}: INT NOT NULL DEFAULT 1 + @AutoGenerated(VERSION)</li>
 *   <li>{@code created}: @AutoGenerated(CREATED_TIMESTAMP)</li>
 *   <li>{@code updated}: @AutoGenerated(UPDATED_TIMESTAMP)</li>
 *   <li>{@code name}: VARCHAR NOT NULL (no default) — must be set</li>
 *   <li>{@code volume}: INT NOT NULL (no default) — must be set</li>
 * </ul>
 * <p>
 * Uses H2 in-memory database. Requires JDK 17+.
 */
public class BatchInsertNullDefaultTest extends AbstractTestBase {

	private static final LambdaTable<Foo> FOO = () -> Foo.class;

	@BeforeEach
	public void truncate() {
		factory.getMetadataFactory().truncate(FOO).execute();
	}

	/**
	 * Core test: batch insert with 'code' field left null.
	 * Column 'code' is VARCHAR(64) NOT NULL DEFAULT ''.
	 * Without AUTO_DEFAULT fix, this would throw NOT NULL constraint violation.
	 * With the fix, null is substituted with "" (empty string).
	 * 
	 * Note: Since CODE has a UNIQUE constraint, we can only have ONE bean with null code
	 * (which gets substituted with ""). Other beans must have explicit unique codes.
	 */
	@Test
	public void testAutoDefault_bulkMode() {
		Foo full = makeFoo("FULL01", "Full Record", 100);

		// code is null → should be substituted with "" by AUTO_DEFAULT
		Foo partial = new Foo();
		partial.setName("Partial Record");
		partial.setVolume(50);
		// code = null, codeType = 0 (primitive default)

		// This bean must have a unique code since CODE column has UNIQUE constraint
		Foo partial2 = makeFoo("FULL02", "Partial2 Record", 30);

		long count = factory.insert(FOO)
				.batchToBulk(true)
				.populateBatch(Arrays.asList(full, partial, partial2))
				.execute();

		assertEquals(3, count, "All 3 records should be inserted in bulk mode");
		CRUDRepository<Foo, Integer> repo = factory.asRepository(FOO);
		List<Foo> results = repo.query().fetch();
		assertEquals(3, results.size());

		// Verify partial record: code should be "" (default), not null
		Foo partialResult = repo.query().eq(Foo::getName, "Partial Record").fetchFirst();
		assertNotNull(partialResult);
		assertEquals("", partialResult.getCode(), "code should be substituted with default empty string");
	}

	/**
	 * Same test in JDBC batch mode (batchToBulk=false).
	 * Only one bean with null code to avoid UNIQUE constraint violation.
	 */
	@Test
	public void testAutoDefault_jdbcBatchMode() {
		Foo full = makeFoo("JDBC01", "JDBC Full", 100);

		Foo partial = new Foo();
		partial.setName("JDBC Partial");
		partial.setVolume(50);
		// code = null → will be substituted with ""

		long count = factory.insert(FOO)
				.batchToBulk(false)
				.populateBatch(Arrays.asList(full, partial))
				.execute();

		assertEquals(2, count, "Both records should be inserted in JDBC batch mode");
	}

	/**
	 * Verify @AutoGenerated(CREATED_TIMESTAMP) and @AutoGenerated(VERSION)
	 * work correctly alongside AUTO_DEFAULT.
	 * Fields 'created', 'updated' should be auto-generated even when null in bean.
	 * Field 'version' should get its @AutoGenerated value (1 for insert).
	 * Only one bean with null code to avoid UNIQUE constraint violation.
	 */
	@Test
	public void testAutoDefault_compatibleWithAutoGenerated() {
		Foo bean1 = new Foo();
		bean1.setName("AutoGen Test1");
		bean1.setVolume(10);
		// code=null → AUTO_DEFAULT substitutes ""
		// created=null → @AutoGenerated fills CURRENT_TIMESTAMP
		// version=0 → @AutoGenerated fills 1

		Foo bean2 = makeFoo("AUTOGEN02", "AutoGen Test2", 20);

		long count = factory.insert(FOO)
				.populateBatch(Arrays.asList(bean1, bean2))
				.execute();

		assertEquals(2, count);

		CRUDRepository<Foo, Integer> repo = factory.asRepository(FOO);
		Foo result = repo.query().eq(Foo::getName, "AutoGen Test1").fetchFirst();
		assertNotNull(result);
		assertNotNull(result.getCreated(), "created should be auto-generated");
		assertNotNull(result.getUpdated(), "updated should be auto-generated");
		assertTrue(result.getVersion() > 0, "version should be auto-generated (>=1)");
		assertEquals("", result.getCode(), "code should be default empty string");
	}

	/**
	 * Test with a larger batch to ensure consistency.
	 * Each bean gets a unique code to avoid UNIQUE constraint violation.
	 */
	@Test
	public void testAutoDefault_largeBatch() {
		int batchSize = 50;
		List<Foo> batch = new java.util.ArrayList<>(batchSize);
		for (int i = 0; i < batchSize; i++) {
			Foo bean = new Foo();
			bean.setCode("batch_code_" + i); // Provide unique code for each bean
			bean.setName("batch_" + i);
			bean.setVolume(i);
			batch.add(bean);
		}

		long count = factory.insert(FOO)
				.populateBatch(batch)
				.execute();

		assertEquals(batchSize, count, "All records should be inserted");
		assertEquals(batchSize, factory.asRepository(FOO).query().count());
	}

	/**
	 * Test codeType field: INT NOT NULL DEFAULT 1.
	 * The codeType field is a primitive int WITHOUT @UnsavedValue annotation.
	 * According to the framework's behavior, primitive types without @UnsavedValue
	 * treat their default value (0 for int) as "unsaved".
	 * Therefore, when codeType=0, it will be substituted with the column's default value (1).
	 * When codeType is explicitly set to a non-zero value (e.g., 5), it will be preserved.
	 * Each bean gets a unique code to avoid UNIQUE constraint violation.
	 */
	@Test
	public void testAutoDefault_intFieldWithDefaultValue() {
		Foo bean = new Foo();
		bean.setCode("INTDEF01");
		bean.setName("IntDefault Test");
		bean.setVolume(10);
		bean.setCodeType(0); // 0 is treated as unsaved for primitive int without @UnsavedValue

		Foo bean2 = new Foo();
		bean2.setCode("INTDEF02");
		bean2.setName("IntDefault Test2");
		bean2.setVolume(20);
		bean2.setCodeType(5); // explicitly set to 5

		long count = factory.insert(FOO)
				.populateBatch(Arrays.asList(bean, bean2))
				.execute();

		assertEquals(2, count);

		CRUDRepository<Foo, Integer> repo = factory.asRepository(FOO);
		Foo result1 = repo.query().eq(Foo::getName, "IntDefault Test").fetchFirst();
		assertNotNull(result1);
		// codeType was 0 (unsaved value for primitive int), should be substituted with default 1
		assertEquals(1, result1.getCodeType(), "codeType=0 is unsaved, should be substituted with default 1");
		
		Foo result2 = repo.query().eq(Foo::getName, "IntDefault Test2").fetchFirst();
		assertNotNull(result2);
		// codeType was explicitly set to 5, should remain 5
		assertEquals(5, result2.getCodeType(), "codeType=5 should be preserved");
	}

	private Foo makeFoo(String code, String name, int volume) {
		Foo f = new Foo();
		f.setCode(code);
		f.setName(name);
		f.setVolume(volume);
		return f;
	}
}
