package com.github.xuse.querydsl.sql.dml;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.github.xuse.querydsl.entity.Foo;
import com.github.xuse.querydsl.lambda.LambdaTable;
import com.github.xuse.querydsl.repository.CRUDRepository;
import com.github.xuse.querydsl.sql.integration.AbstractTestBase;

/**
 * Integration test to verify whether {@link SQLInsertClauseAlter#populateAutoGeneratedColumns()}
 * is still needed when using the set() API (as opposed to populate()).
 * <p>
 * Scenario: insert via set() without calling populateAutoGeneratedColumns(),
 * then insert via set() WITH calling populateAutoGeneratedColumns().
 * Compare whether @AutoGenerated fields (created, updated, version) are filled.
 */
public class PopulateAutoGeneratedColumnsTest extends AbstractTestBase {

	private static final LambdaTable<Foo> FOO = () -> Foo.class;

	@BeforeEach
	public void truncate() {
		factory.getMetadataFactory().truncate(FOO).execute();
	}

	/**
	 * Insert using set() — with default writeAutoColumns=true, @AutoGenerated fields
	 * should be auto-filled during execute() without explicit call.
	 */
	@Test
	public void testSetDefault_autoFillsDuringExecute() {
		long count = factory.insert(FOO)
				.set(Foo::getCode, "SET_DEFAULT_01")
				.set(Foo::getName, "Default Auto Gen")
				.set(Foo::getVolume, 100)
				.execute();

		assertEquals(1, count);

		CRUDRepository<Foo, Integer> repo = factory.asRepository(FOO);
		Foo result = repo.query().eq(Foo::getCode, "SET_DEFAULT_01").fetchFirst();
		assertNotNull(result);

		// With writeAutoColumns=true (default), execute() auto-populates @AutoGenerated fields
		assertNotNull(result.getCreated(), "created should be auto-generated by default");
		assertNotNull(result.getUpdated(), "updated should be auto-generated by default");
		assertEquals(1, result.getVersion(), "version should be auto-generated as 1 by default");
	}

	/**
	 * Insert using set() with writeAutoColumns(false) — @AutoGenerated fields
	 * should NOT be auto-filled.
	 */
	@Test
	public void testSetWithWriteAutoColumnsFalse_noAutoFill() {
		long count = factory.insert(FOO)
				.set(Foo::getCode, "SET_NO_AUTO_01")
				.set(Foo::getName, "No Auto Gen")
				.set(Foo::getVolume, 100)
				.writeAutoColumns(false)
				.execute();

		assertEquals(1, count);

		CRUDRepository<Foo, Integer> repo = factory.asRepository(FOO);
		Foo result = repo.query().eq(Foo::getCode, "SET_NO_AUTO_01").fetchFirst();
		assertNotNull(result);

		// With writeAutoColumns=false, these should NOT be filled by framework
		assertNull(result.getCreated(), "created should be null with writeAutoColumns(false)");
		assertNull(result.getUpdated(), "updated should be null with writeAutoColumns(false)");
		// version gets DB default 1, but NOT from @AutoGenerated logic
		assertEquals(1, result.getVersion(), "version gets DB default 1, not from @AutoGenerated");
	}

	/**
	 * Insert using populate(bean) — should auto-fill without needing populateAutoGeneratedColumns().
	 * This confirms that populate() path already handles @AutoGenerated internally.
	 */
	@Test
	public void testPopulate_autoFillsWithoutExplicitCall() {
		Foo bean = new Foo();
		bean.setCode("POPULATE_01");
		bean.setName("Populate Auto");
		bean.setVolume(300);
		// created, updated, version are not set

		long count = factory.insert(FOO)
				.populate(bean)
				.execute();

		assertEquals(1, count);

		CRUDRepository<Foo, Integer> repo = factory.asRepository(FOO);
		Foo result = repo.query().eq(Foo::getCode, "POPULATE_01").fetchFirst();
		assertNotNull(result);

		// populate() should auto-fill @AutoGenerated fields via AdvancedMapper
		assertNotNull(result.getCreated(), "created should be auto-generated via populate()");
		assertNotNull(result.getUpdated(), "updated should be auto-generated via populate()");
		assertEquals(1, result.getVersion(), "version should be auto-generated as 1 via populate()");
	}
}
