package com.github.xuse.querydsl.entity.partition;

import java.sql.Types;
import java.util.Date;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.UnsavedValue;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.Comment;
import com.github.xuse.querydsl.annotation.dbdef.Key;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;
import com.github.xuse.querydsl.annotation.partition.Partition;
import com.github.xuse.querydsl.annotation.partition.RangePartition;
import com.github.xuse.querydsl.sql.ddl.ConstraintType;

import lombok.Data;

@Data
@TableSpec(name="partition_test2",primaryKeys={"id","created"},collate = "utf8mb4_general_ci",
	keys = {
		@Key(path= {"name"},type=ConstraintType.KEY)
	}
)
@Comment("Test table for partition.")
@RangePartition(
	columns="created",
	value={
		@Partition(name = "p202405",value="'2024-06-01'", from="'2024-01-01'"),
		@Partition(name = "p202406",value="'2024-07-01'", from="'2024-06-01'"),
		@Partition(name = "p202407",value="'2024-08-01'", from="'2024-07-01'"),
		@Partition(name = "pmax",value="MAXVALUE", from ="'2024-08-01'"),
	}
)
public class PartitionFoo2 {
	@UnsavedValue(UnsavedValue.ZeroAndMinus)
	@ColumnSpec(autoIncrement = true,type = Types.INTEGER,unsigned = true,nullable = false)
	@Comment("primary key，auto increment.")
	private int id;
	
	@ColumnSpec(type = Types.VARCHAR,size=64,nullable = false,defaultValue = "''")
	@Comment("The code of asset. unique.")
	private String code;
	
	@ColumnSpec(name="asset_name",size=128,nullable = false)
	@Comment("The name of the asset.")
	private String name;
	
	@ColumnSpec(nullable = false)
	@AutoGenerated(GeneratedType.CREATED_TIMESTAMP)
	@Comment("create time of the record.")
	private Date created;
	
	@ColumnSpec(nullable = false)
	@AutoGenerated(GeneratedType.UPDATED_TIMESTAMP)
	@Comment("update time of the record.")
	private Date updated;
}
