package com.github.xuse.querydsl.entity.partition;

import java.sql.Types;
import java.util.Date;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.UnsavedValue;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.Comment;
import com.github.xuse.querydsl.annotation.dbdef.Key;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;
import com.github.xuse.querydsl.annotation.partition.AutoTimePartitions;
import com.github.xuse.querydsl.annotation.partition.ColumnFormat;
import com.github.xuse.querydsl.annotation.partition.Period;
import com.github.xuse.querydsl.annotation.partition.RangePartition;
import com.github.xuse.querydsl.sql.ddl.ConstraintType;

import lombok.Data;

@Data
@TableSpec(name="partition_test1b",primaryKeys={"id","recordTime"},collate = "utf8mb4_general_ci",
	keys = {
		@Key(path= {"name"},type=ConstraintType.KEY)
	}
)
@Comment("Test table for partition.")
@RangePartition(
	columns = "recordTime", 
	auto = @AutoTimePartitions(
		unit = Period.DAY,
		periodsBegin = -2,
		periodsEnd = 3,
		createForMaxValue = true,
		columnFormat = ColumnFormat.NUMBER_YMD
	)
)
public class PartitionFoo1b {
	@ColumnSpec(autoIncrement = true,type = Types.INTEGER,unsigned = true,nullable = false)
	@Comment("primary key，auto increment.")
	@UnsavedValue(UnsavedValue.ZeroAndMinus)
	private int id;
	
	@ColumnSpec(type = Types.VARCHAR,size=64,nullable = false,defaultValue = "''")
	@Comment("The code of asset. unique.")
	private String code;
	
	@ColumnSpec(name="asset_name",size=128,nullable = false)
	@Comment("The name of the asset.")
	private String name;
	
	@ColumnSpec(name="record_time",nullable = false)
	@Comment("The time number of the asset.")
	private int recordTime;
	
	@ColumnSpec(nullable = false)
	@AutoGenerated(GeneratedType.CREATED_TIMESTAMP)
	@Comment("create time of the record.")
	private Date created;
	
	@ColumnSpec(nullable = false)
	@AutoGenerated(GeneratedType.UPDATED_TIMESTAMP)
	@Comment("update time of the record.")
	private Date updated;
}
