package com.github.xuse.querydsl.r2dbc.jdbcwrapper;

import java.sql.*;

public abstract class UnsupportedJdbcStatement implements PreparedStatement{
	public ResultSet executeQuery() {
		throw new UnsupportedOperationException();
	}

	public int executeUpdate() {
		throw new UnsupportedOperationException();
	}
	
	public ResultSetMetaData getMetaData() {
		throw  new UnsupportedOperationException();
	}

	/* JDBC_4_ANT_KEY_END */
	@Override
	public ResultSet executeQuery(String sql) {
		throw new UnsupportedOperationException();
	}

	@Override
	public int executeUpdate(String sql) {
		throw new UnsupportedOperationException();
	}


	@Override
	public int getMaxFieldSize() {
		throw new UnsupportedOperationException();
	}

	@Override
	public void setMaxFieldSize(int max) {
		throw new UnsupportedOperationException();
	}

	@Override
	public void cancel() {
		throw new UnsupportedOperationException();		
	}

	@Override
	public void clearWarnings() {
		throw new UnsupportedOperationException();
	}

	@Override
	public void setCursorName(String name) {
		throw new UnsupportedOperationException();
	}

	@Override
	public boolean execute(String sql) {
		throw new UnsupportedOperationException();
	}

	@Override
	public ResultSet getResultSet() {
		throw new UnsupportedOperationException();
	}

	@Override
	public int getUpdateCount() {
		throw new UnsupportedOperationException();
	}


	@Override
	public SQLWarning getWarnings() {
		return null;
	}

	
	@Override
	public boolean getMoreResults() {
		throw new UnsupportedOperationException();
	}

	@Override
	public void setFetchDirection(int direction) {
		throw new UnsupportedOperationException();
	}

	@Override
	public int getFetchDirection() {
		throw new UnsupportedOperationException();
	}


	@Override
	public void addBatch(String sql) {
		throw new UnsupportedOperationException();
	}

	@Override
	public void clearBatch() {
		throw new UnsupportedOperationException();
	}

	@Override
	public int[] executeBatch() {
		throw new UnsupportedOperationException();
	}

	@Override
	public Connection getConnection() {
		throw new UnsupportedOperationException();
	}


	@Override
	public boolean getMoreResults(int current) {
		throw new UnsupportedOperationException();
	}

	@Override
	public ResultSet getGeneratedKeys() {
		throw new UnsupportedOperationException();
	}

	@Override
	public int executeUpdate(String sql, int autoGeneratedKeys) {
		throw new UnsupportedOperationException();		
	}

	@Override
	public int executeUpdate(String sql, int[] columnIndexes) {
		throw new UnsupportedOperationException();
	}

	@Override
	public int executeUpdate(String sql, String[] columnNames) {
		throw new UnsupportedOperationException();		
	}

	@Override
	public boolean execute(String sql, int autoGeneratedKeys) {
		throw new UnsupportedOperationException();		
	}

	@Override
	public boolean execute(String sql, int[] columnIndexes) {
		throw new UnsupportedOperationException();
	}

	@Override
	public boolean execute(String sql, String[] columnNames) {
		throw new UnsupportedOperationException();
	}


	public java.sql.ParameterMetaData getParameterMetaData() {
		throw new UnsupportedOperationException();
	}
	
}
