package com.github.xuse.querydsl.sql.expression;

import java.util.List;
import java.util.UUID;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.config.SnowflakeIdManager;
import com.github.xuse.querydsl.sql.column.ColumnMapping;
import com.github.xuse.querydsl.util.Entry;
import com.github.xuse.querydsl.util.Exceptions;
import com.github.xuse.querydsl.util.SnowflakeIdWorker;
import com.github.xuse.querydsl.util.StringUtils;
import com.querydsl.core.types.Expression;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.Expressions;
import com.querydsl.core.types.dsl.NumberPath;
import com.querydsl.sql.PrimaryKey;
import com.querydsl.sql.RelationalPath;

public abstract class AbstractMapperSupport {

	public static final int SCENARIO_NORMAL = 0;
	public static final int SCENARIO_INSERT = 1;
	public static final int SCENARIO_UPDATE = 2;
	
	public static boolean isUnsavedValue(ColumnMapping columnMetadata, Object value) {
		if (value instanceof Expression<?>) {
			return false;
		}
		return columnMetadata.isUnsavedValue(value);
	}

	/**
	 * Sentinel returned by {@link #resolveAutoGenerated} to indicate no auto-generated value was applied.
	 * <p>
	 * {@link #resolveAutoGenerated} 未产生自动生成值时返回的哨兵。
	 */
	public static final Object NO_AUTO_VALUE = new Object();

	/**
	 * Resolve the {@code @AutoGenerated} value for a column and, if applicable, write it back to the bean.
	 * Shared by the map-based mapper and the bulk value-group builder to avoid duplicating the auto-value logic.
	 * <p>
	 * Applies only when the column has an {@code @AutoGenerated} definition and either {@code overwrite()} is
	 * set or the current value is unsaved. Writeback is delegated to {@link ColumnMapping#writeback} which
	 * itself handles expression values (e.g. {@code current_timestamp}).
	 * <p>
	 * 解析列的 {@code @AutoGenerated} 值并在需要时回写到 bean。map 映射器与 bulk 取值组装器共用此逻辑，避免重复。
	 * 仅当列定义了 {@code @AutoGenerated} 且 {@code overwrite()} 或当前值无效时生效。回写交由
	 * {@link ColumnMapping#writeback} 处理（其内部会处理 {@code current_timestamp} 等表达式值）。
	 *
	 * @param metadata the column mapping
	 * @param unsaved  whether the current value is unsaved/invalid
	 * @param scenario the operation scenario (insert/update)
	 * @param bean     the bean to write back to
	 * @return the generated value (already written back if configured), or {@link #NO_AUTO_VALUE} if not applied
	 */
	public static Object resolveAutoGenerated(ColumnMapping metadata, boolean unsaved, int scenario, Object bean) {
		AutoGenerated generated = metadata.getGenerated();
		if (generated == null || !(generated.overwrite() || unsaved)) {
			return NO_AUTO_VALUE;
		}
		Object autoValue = asAutoValue(generated, metadata, scenario);
		if (autoValue == null) {
			return NO_AUTO_VALUE;
		}
		if (generated.writeback()) {
			metadata.writeback(bean, autoValue);
		}
		return autoValue;
	}

	/*
	 * Nullable columnMapping
	 */
	protected void processNullBindings(Path<?> p, List<Entry<Path<?>, Object>> data, ColumnMapping columnMapping) {
	}

	protected static boolean isKeyColumn(Path<?> path) {
		Path<?> parent = path.getMetadata().getParent();
		// 计算列是不是主键字段，如果是主键字段那么为null时，也不尝试更新。因为数据库主键天然的不允许为NULL。
		if (parent instanceof RelationalPath) {
			PrimaryKey<?> pk = ((RelationalPath<?>) parent).getPrimaryKey();
			return pk != null && pk.getLocalColumns().contains(path);
		}
		return false;
	}

	// 根据自动生成值注解返回要写入的自动数据
	/**
	 * @param generateDef generateDef
	 * @param metadata    可能为NULL。当用户使用非默认的bean进行数据库操作时，该字段可能为null
	 * @param scenario scenario
	 * @return Object
	 */
	public static Object asAutoValue(AutoGenerated generateDef, ColumnMapping metadata, int scenario) {
		switch(generateDef.value()) {
			case CREATED_TIMESTAMP:
				if (scenario == SCENARIO_INSERT) {
					return Expressions.currentTimestamp();
				}
				break;
			case UPDATED_TIMESTAMP:
				if (scenario > 0) {
					return Expressions.currentTimestamp();
				}
				break;
			case GUID36:
				if (scenario == SCENARIO_INSERT) {
					UUID uuid = UUID.randomUUID();
					return uuid.toString();
				}
				break;
			case GUID32:
				if (scenario == SCENARIO_INSERT) {
					return StringUtils.generateGuid32();
				}
				break;
			case VERSION:
				if (scenario == SCENARIO_INSERT) {
					Class<?> type= metadata.getType();
					if(type==Long.class || type==Long.TYPE) {
						return 1L;
					}else {
						return 1;
					}
				}else if(scenario==SCENARIO_UPDATE){
					Path<?> path= metadata.getPath();
					if(path instanceof NumberPath) {
						return ((NumberPath<?>)path).add(Expressions.ONE);
					}else {
						throw Exceptions.illegalArgument("A 'Version' field must be defined as a NumberPath. field={}", metadata.getColumn());
					}
				}
				break;
			case SNOWFLAKE:
				if (scenario == SCENARIO_INSERT) {
					SnowflakeIdWorker worker;
					if ((worker = SnowflakeIdManager.getInstance()) != null) {
						return worker.nextId();
					} else {
						throw Exceptions.illegalArgument("Please init snowflake workerId and datacenterId for @AutoGenerated type 'SNOWFLAKE'!");
					}
				}
				break;
			default:
				throw new IllegalArgumentException("Unsupported auto-generate type:" + generateDef.value());
		}
		return null;
	}
}
