package com.github.xuse.querydsl.sql.expression;

import java.util.function.Function;

import com.github.xuse.querydsl.annotation.query.PathBinder;
import com.github.xuse.querydsl.sql.RelationalPathEx;
import com.github.xuse.querydsl.util.TypeUtils;
import com.github.xuse.querydsl.util.Util;
import com.querydsl.core.types.Path;

/**
 * <h2>English:</h2>
 * A wrapper that adapts a DTO object for use with {@link AdvancedMapper}.
 * <p>
 * When passed to {@code populate()}, the {@link AdvancedMapper#getBeanCodec} method
 * recognizes this wrapper and produces values aligned with the table's column order,
 * applying field name remapping and type conversion based on {@link PathBinder} annotations.
 * </p>
 * <p>
 * This allows all existing AdvancedMapper logic (null strategies, {@code @AutoGenerated},
 * {@code @UnsavedValue}, {@code notInsert}/{@code notUpdate}) to work transparently.
 * </p>
 *
 * <h2>Chinese:</h2>
 * 将 DTO 对象包装后传入 {@link AdvancedMapper} 使用的适配器。
 * <p>
 * 传入 {@code populate()} 时，{@link AdvancedMapper#getBeanCodec} 识别此包装，
 * 按表列顺序生成值数组，并根据 {@link PathBinder} 注解进行字段名映射和类型转换。
 * </p>
 * <p>
 * 这使得 AdvancedMapper 的所有现有逻辑（null 策略、{@code @AutoGenerated}、
 * {@code @UnsavedValue}、{@code notInsert}/{@code notUpdate}）都能透明工作。
 * </p>
 *
 * <p>Usage:</p>
 * <pre>
 * factory.insert(fooPath).populate(ConverterWrappedBean.of(fooDTO)).execute();
 * factory.update(fooPath).populate(ConverterWrappedBean.of(fooDTO), true).execute();
 * </pre>
 *
 * @author Joey
 */
public class ConverterWrappedBean {

	private final Object dto;
	private final Class<?> dtoType;

	private ConverterWrappedBean(Object dto) {
		this.dto = dto;
		this.dtoType = dto.getClass();
	}

	/**
	 * Wrap a DTO object for use with populate().
	 *
	 * @param dto the DTO object with optional {@link PathBinder} annotations
	 * @return wrapped bean
	 */
	public static ConverterWrappedBean of(Object dto) {
		return new ConverterWrappedBean(dto);
	}

	/**
	 * Get the underlying DTO object.
	 */
	public Object getDto() {
		return dto;
	}

	/**
	 * Get the DTO class.
	 */
	public Class<?> getDtoType() {
		return dtoType;
	}

	/**
	 * Extract values from the DTO, aligned with the given table's column order.
	 * Applies @PathBinder field name remapping and writeConverter.
	 *
	 * @param entity the target table
	 * @return values array aligned with entity.getColumns() order
	 */
	@SuppressWarnings({ "rawtypes", "unchecked" })
	public Object[] extractValues(RelationalPathEx<?> entity) {
		// Get DTO's full BeanCodec (cached)
		BeanCodec dtoCodec = BeanCodecManager.getInstance().getCodec(dtoType);
		Property[] dtoFields = dtoCodec.getFields();
		Object[] dtoValues = dtoCodec.values(dto);

		// Build a lookup: sourceName -> (value, writeConverter)
		// sourceName is the entity field name that this DTO field maps to
		java.util.Map<String, Object> valueMap = new java.util.HashMap<>(dtoFields.length);
		java.util.Map<String, Function> converterMap = new java.util.HashMap<>();

		for (int i = 0; i < dtoFields.length; i++) {
			Property field = dtoFields[i];
			PathBinder pathBinder = field.getAnnotation(PathBinder.class);

			// Skip non-writable fields
			if (pathBinder != null && !pathBinder.writable()) {
				continue;
			}

			String targetName = (pathBinder != null) ? pathBinder.value() : field.getName();
			valueMap.put(targetName, dtoValues[i]);

			// Resolve write converter
			if (pathBinder != null) {
				Function converter = resolveWriteConverter(pathBinder, field);
				if (converter != null) {
					converterMap.put(targetName, converter);
				}
			}
		}

		// Build result array aligned with entity columns
		java.util.List<Path<?>> columns = entity.getColumns();
		Object[] result = new Object[columns.size()];
		for (int i = 0; i < columns.size(); i++) {
			String colName = columns.get(i).getMetadata().getName();
			if (valueMap.containsKey(colName)) {
				Object value = valueMap.get(colName);
				Function converter = converterMap.get(colName);
				if (converter != null && value != null) {
					value = converter.apply(value);
				}
				result[i] = value;
			}
			// else: leave as null (DTO doesn't have this field)
		}
		return result;
	}

	@SuppressWarnings("rawtypes")
	private Function resolveWriteConverter(PathBinder pathBinder, Property field) {
		Class<? extends Function> writeClass = pathBinder.writeConverter();
		if (writeClass != Function.class) {
			return (Function) TypeUtils.newInstance(writeClass);
		}
		String ref = pathBinder.writeConverterRef();
		if (!ref.isEmpty()) {
			return Util.getStaticFunctionField(dtoType, ref, field.getName());
		}
		return null;
	}
}
