package com.github.xuse.querydsl.sql.expression;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;

import com.github.xuse.querydsl.annotation.query.PathBinder;
import com.github.xuse.querydsl.config.ConfigurationEx;
import com.github.xuse.querydsl.sql.RelationalPathEx;
import com.github.xuse.querydsl.util.TypeUtils;
import com.github.xuse.querydsl.util.Util;
import com.github.xuse.querydsl.util.collection.MapCreator;
import com.querydsl.core.types.Path;

/**
 * <h2>English:</h2>
 * A wrapper that adapts a DTO object for use with {@link AdvancedMapper}.
 * <p>
 * When a DTO with {@link PathBinder} annotations is passed to {@code populate()},
 * the framework automatically detects and handles field name remapping and type conversion.
 * All existing AdvancedMapper logic (null strategies, {@code @AutoGenerated},
 * {@code @UnsavedValue}, {@code notInsert}/{@code notUpdate}) works transparently.
 * </p>
 * <p>
 * Users can also explicitly wrap a DTO via {@link #of(Object)} for clarity.
 * </p>
 *
 * <h2>Chinese:</h2>
 * 将 DTO 对象适配到 {@link AdvancedMapper} 使用的工具类。
 * <p>
 * 当带有 {@link PathBinder} 注解的 DTO 传入 {@code populate()} 时，
 * 框架自动检测并处理字段名映射和类型转换。
 * AdvancedMapper 的所有现有逻辑（null 策略、{@code @AutoGenerated}、
 * {@code @UnsavedValue}、{@code notInsert}/{@code notUpdate}）都能透明工作。
 * </p>
 *
 * <p>Usage:</p>
 * <pre>
 * // Explicit wrapping (optional)
 * factory.insert(fooPath).populate(ConverterWrappedBean.of(fooDTO)).execute();
 *
 * // Or just pass the DTO directly - auto-detected if it has @PathBinder annotations
 * factory.insert(fooPath).populate(fooDTO).execute();
 * </pre>
 *
 * @author Joey
 */
public class ConverterWrappedBean {

	/** Cache: classes that have been checked for @PathBinder presence. */
	private static final Set<Class<?>> HAS_PATH_BINDER = ConcurrentHashMap.newKeySet();
	private static final Set<Class<?>> NO_PATH_BINDER = ConcurrentHashMap.newKeySet();

	/**
	 * Cache: (dtoType, entityType) -> DtoMappingInfo.
	 * Contains both the BeanCodec and the FieldSlot[] aligned with entity columns.
	 */
	private static final Map<ClassPairKey, DtoMappingInfo> MAPPING_CACHE = MapCreator.createConcurrentMap(ConfigurationEx.WRAPPERED_BEAN_CACHE_SIZE);

	private final Object dto;
	private final Class<?> dtoType;

	private ConverterWrappedBean(Object dto) {
		this.dto = dto;
		this.dtoType = dto.getClass();
	}

	/**
	 * Wrap a DTO object explicitly.
	 *
	 * @param dto the DTO object with {@link PathBinder} annotations
	 * @return wrapped bean
	 */
	public static ConverterWrappedBean of(Object dto) {
		return new ConverterWrappedBean(dto);
	}

	/**
	 * Check if a class has any {@link PathBinder} annotations on its fields.
	 * Result is cached for performance.
	 *
	 * @param clazz the class to check
	 * @return true if any field has @PathBinder
	 */
	public static boolean hasPathBinder(Class<?> clazz) {
		if (HAS_PATH_BINDER.contains(clazz)) {
			return true;
		}
		if (NO_PATH_BINDER.contains(clazz)) {
			return false;
		}
		// Check via BeanCodec (cached)
		BeanCodec codec = BeanCodecManager.getInstance().getCodec(clazz);
		for (Property field : codec.getFields()) {
			if (field.getAnnotation(PathBinder.class) != null) {
				HAS_PATH_BINDER.add(clazz);
				return true;
			}
		}
		NO_PATH_BINDER.add(clazz);
		return false;
	}

	/**
	 * Get the underlying DTO object.
	 */
	public Object getDto() {
		return dto;
	}

	/**
	 * Create a {@link ValueExtractor} for batch processing.
	 * The extractor produces values aligned with the given column path list
	 * (typically the constantPath from BatchProcessor).
	 *
	 * @param entity the target table (for resolving field mappings)
	 * @param paths  the column paths to extract values for (subset of entity columns)
	 * @return a ValueExtractor that handles DTO beans of this type
	 */
	public ValueExtractor toValueExtractor(RelationalPathEx<?> entity, List<Path<?>> paths) {
		DtoMappingInfo info = getMapping(dtoType, entity);
		// Build index mapping: for each path in 'paths', find the corresponding FieldSlot
		List<Path<?>> allColumns = entity.getColumns();
		int[] columnIndices = new int[paths.size()];
		for (int i = 0; i < paths.size(); i++) {
			String name = paths.get(i).getMetadata().getName();
			int found = -1;
			for (int c = 0; c < allColumns.size(); c++) {
				if (allColumns.get(c).getMetadata().getName().equals(name)) {
					found = c;
					break;
				}
			}
			columnIndices[i] = found;
		}
		return new DtoValueExtractor(dtoType, info, columnIndices);
	}

	/**
	 * Extract values from the wrapped DTO, aligned with the given table's column order.
	 *
	 * @param entity the target table
	 * @return values array aligned with entity.getColumns() order
	 */
	public Object[] extractValues(RelationalPathEx<?> entity) {
		return extractValues(dto, dtoType, entity);
	}

	/**
	 * Extract values from a DTO object, aligned with the given table's column order.
	 * Applies @PathBinder field name remapping and writeConverter.
	 *
	 * @param bean   the DTO object
	 * @param entity the target table
	 * @return values array aligned with entity.getColumns() order
	 */
	public static Object[] extractValues(Object bean, RelationalPathEx<?> entity) {
		return extractValues(bean, bean.getClass(), entity);
	}

	/**
	 * Core extraction logic. Uses cached DtoMappingInfo (BeanCodec + FieldSlot[]) aligned
	 * with entity column order for O(n) value extraction without any lookup at runtime.
	 */
	@SuppressWarnings({ "rawtypes", "unchecked" })
	private static Object[] extractValues(Object bean, Class<?> dtoType, RelationalPathEx<?> entity) {
		DtoMappingInfo info = getMapping(dtoType, entity);
		Object[] dtoValues = info.codec.values(bean);
		FieldSlot[] slots = info.slots;

		Object[] result = new Object[slots.length];
		for (int i = 0; i < slots.length; i++) {
			FieldSlot slot = slots[i];
			if (slot == null) {
				continue;
			}
			result[i] = slot.writeConverter.apply(dtoValues[slot.dtoFieldIndex]);
		}
		return result;
	}

	/**
	 * Get or build the cached DtoMappingInfo for a (dtoType, entityType) pair.
	 */
	@SuppressWarnings("rawtypes")
	private static DtoMappingInfo getMapping(Class<?> dtoType, RelationalPathEx<?> entity) {
		ClassPairKey key = new ClassPairKey(dtoType, entity.getType());
		DtoMappingInfo cached = MAPPING_CACHE.get(key);
		if (cached != null) {
			return cached;
		}
		// Build DTO field info: targetName -> (dtoFieldIndex, writeConverter)
		BeanCodec codec = BeanCodecManager.getInstance().getCodec(dtoType);
		Property[] fields = codec.getFields();
		Map<String, FieldSlot> fieldMap = new HashMap<>(fields.length);

		for (int i = 0; i < fields.length; i++) {
			Property field = fields[i];
			PathBinder pathBinder = field.getAnnotation(PathBinder.class);

			// Skip non-writable fields
			if (pathBinder != null && !pathBinder.writable()) {
				continue;
			}
			String targetName = (pathBinder != null) ? pathBinder.value() : field.getName();
			Function writeConverter = resolveWriteConverter(dtoType, pathBinder, field);
			fieldMap.put(targetName, new FieldSlot(i, writeConverter));
		}

		// Build result aligned with entity column order
		List<Path<?>> columns = entity.getColumns();
		FieldSlot[] slots = new FieldSlot[columns.size()];
		for (int c = 0; c < columns.size(); c++) {
			String colName = columns.get(c).getMetadata().getName();
			slots[c] = fieldMap.get(colName);
		}
		DtoMappingInfo info = new DtoMappingInfo(codec, slots);
		MAPPING_CACHE.put(key, info);
		return info;
	}

	@SuppressWarnings("rawtypes")
	private static Function resolveWriteConverter(Class<?> dtoType, PathBinder pathBinder, Property field) {
		if (pathBinder == null) {
			return Function.identity();
		}
		Class<? extends Function> writeClass = pathBinder.writeConverter();
		if (writeClass != Function.class) {
			return (Function) TypeUtils.newInstance(writeClass);
		}
		String ref = pathBinder.writeConverterRef();
		if (!ref.isEmpty()) {
			return Util.getStaticFunctionField(dtoType, ref, field.getName());
		}
		return Function.identity();
	}

	/**
	 * Cached mapping info for a (dtoType, entityType) pair.
	 * Holds both the BeanCodec (for value extraction) and the FieldSlot[] (for column alignment).
	 */
	private static final class DtoMappingInfo {
		final BeanCodec codec;
		final FieldSlot[] slots;

		DtoMappingInfo(BeanCodec codec, FieldSlot[] slots) {
			this.codec = codec;
			this.slots = slots;
		}
	}

	/**
	 * A ValueExtractor that extracts DTO values aligned with a specific column path subset.
	 * Used by BatchProcessor for batch insert with DTO beans.
	 */
	@SuppressWarnings({ "rawtypes", "unchecked" })
	private static final class DtoValueExtractor extends ValueExtractor {
		private final Class<?> dtoType;
		private final DtoMappingInfo info;
		/** Maps each output position to an index in the full entity column slots array. -1 means no mapping. */
		private final int[] columnIndices;

		DtoValueExtractor(Class<?> dtoType, DtoMappingInfo info, int[] columnIndices) {
			this.dtoType = dtoType;
			this.info = info;
			this.columnIndices = columnIndices;
		}

		@Override
		public Class<?> getType() {
			return dtoType;
		}

		@Override
		public Object[] values(Object bean) {
			Object actual = (bean instanceof ConverterWrappedBean) ? ((ConverterWrappedBean) bean).getDto() : bean;
			Object[] dtoValues = info.codec.values(actual);
			FieldSlot[] slots = info.slots;
			Object[] result = new Object[columnIndices.length];
			for (int i = 0; i < columnIndices.length; i++) {
				int colIdx = columnIndices[i];
				if (colIdx >= 0) {
					FieldSlot slot = slots[colIdx];
					if (slot != null) {
						result[i] = slot.writeConverter.apply(dtoValues[slot.dtoFieldIndex]);
					}
				}
			}
			return result;
		}

		@Override
		public boolean isInstance(Object bean) {
			Object actual = (bean instanceof ConverterWrappedBean) ? ((ConverterWrappedBean) bean).getDto() : bean;
			return dtoType.isInstance(actual);
		}
	}

	/**
	 * Cached mapping for a single entity column, pointing back to the DTO field index.
	 */
	private static final class FieldSlot {
		/** Index into the DTO's BeanCodec values array. */
		final int dtoFieldIndex;
		@SuppressWarnings("rawtypes")
		final Function writeConverter;

		@SuppressWarnings("rawtypes")
		FieldSlot(int dtoFieldIndex, Function writeConverter) {
			this.dtoFieldIndex = dtoFieldIndex;
			this.writeConverter = writeConverter;
		}
	}

}
