package com.github.xuse.querydsl.sql.expression;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Function;

import com.github.xuse.querydsl.annotation.query.PathBinder;
import com.github.xuse.querydsl.sql.RelationalPathEx;
import com.github.xuse.querydsl.util.TypeUtils;
import com.github.xuse.querydsl.util.Util;
import com.querydsl.core.types.Path;

/**
 * <h2>English:</h2>
 * A wrapper that adapts a DTO object for use with {@link AdvancedMapper}.
 * <p>
 * When a DTO with {@link PathBinder} annotations is passed to {@code populate()},
 * the framework automatically detects and handles field name remapping and type conversion.
 * All existing AdvancedMapper logic (null strategies, {@code @AutoGenerated},
 * {@code @UnsavedValue}, {@code notInsert}/{@code notUpdate}) works transparently.
 * </p>
 * <p>
 * Users can also explicitly wrap a DTO via {@link #of(Object)} for clarity.
 * </p>
 *
 * <h2>Chinese:</h2>
 * 将 DTO 对象适配到 {@link AdvancedMapper} 使用的工具类。
 * <p>
 * 当带有 {@link PathBinder} 注解的 DTO 传入 {@code populate()} 时，
 * 框架自动检测并处理字段名映射和类型转换。
 * AdvancedMapper 的所有现有逻辑（null 策略、{@code @AutoGenerated}、
 * {@code @UnsavedValue}、{@code notInsert}/{@code notUpdate}）都能透明工作。
 * </p>
 *
 * <p>Usage:</p>
 * <pre>
 * // Explicit wrapping (optional)
 * factory.insert(fooPath).populate(ConverterWrappedBean.of(fooDTO)).execute();
 *
 * // Or just pass the DTO directly - auto-detected if it has @PathBinder annotations
 * factory.insert(fooPath).populate(fooDTO).execute();
 * </pre>
 *
 * @author Joey
 */
public class ConverterWrappedBean {

	/** Cache: classes that have been checked for @PathBinder presence. */
	private static final Set<Class<?>> HAS_PATH_BINDER = ConcurrentHashMap.newKeySet();
	private static final Set<Class<?>> NO_PATH_BINDER = ConcurrentHashMap.newKeySet();

	private final Object dto;
	private final Class<?> dtoType;

	private ConverterWrappedBean(Object dto) {
		this.dto = dto;
		this.dtoType = dto.getClass();
	}

	/**
	 * Wrap a DTO object explicitly.
	 *
	 * @param dto the DTO object with {@link PathBinder} annotations
	 * @return wrapped bean
	 */
	public static ConverterWrappedBean of(Object dto) {
		return new ConverterWrappedBean(dto);
	}

	/**
	 * Check if a class has any {@link PathBinder} annotations on its fields.
	 * Result is cached for performance.
	 *
	 * @param clazz the class to check
	 * @return true if any field has @PathBinder
	 */
	public static boolean hasPathBinder(Class<?> clazz) {
		if (HAS_PATH_BINDER.contains(clazz)) {
			return true;
		}
		if (NO_PATH_BINDER.contains(clazz)) {
			return false;
		}
		// Check via BeanCodec (cached)
		BeanCodec codec = BeanCodecManager.getInstance().getCodec(clazz);
		for (Property field : codec.getFields()) {
			if (field.getAnnotation(PathBinder.class) != null) {
				HAS_PATH_BINDER.add(clazz);
				return true;
			}
		}
		NO_PATH_BINDER.add(clazz);
		return false;
	}

	/**
	 * Get the underlying DTO object.
	 */
	public Object getDto() {
		return dto;
	}

	/**
	 * Extract values from the wrapped DTO, aligned with the given table's column order.
	 *
	 * @param entity the target table
	 * @return values array aligned with entity.getColumns() order
	 */
	public Object[] extractValues(RelationalPathEx<?> entity) {
		return extractValues(dto, dtoType, entity);
	}

	/**
	 * Extract values from a DTO object, aligned with the given table's column order.
	 * Applies @PathBinder field name remapping and writeConverter.
	 *
	 * @param bean   the DTO object
	 * @param entity the target table
	 * @return values array aligned with entity.getColumns() order
	 */
	public static Object[] extractValues(Object bean, RelationalPathEx<?> entity) {
		return extractValues(bean, bean.getClass(), entity);
	}

	@SuppressWarnings({ "rawtypes", "unchecked" })
	private static Object[] extractValues(Object bean, Class<?> dtoType, RelationalPathEx<?> entity) {
		// Get DTO's full BeanCodec (cached)
		BeanCodec dtoCodec = BeanCodecManager.getInstance().getCodec(dtoType);
		Property[] dtoFields = dtoCodec.getFields();
		Object[] dtoValues = dtoCodec.values(bean);

		// Build a lookup: targetName (entity field name) -> value
		Map<String, Object> valueMap = new HashMap<>(dtoFields.length);
		Map<String, Function> converterMap = new HashMap<>();

		for (int i = 0; i < dtoFields.length; i++) {
			Property field = dtoFields[i];
			PathBinder pathBinder = field.getAnnotation(PathBinder.class);

			// Skip non-writable fields
			if (pathBinder != null && !pathBinder.writable()) {
				continue;
			}

			String targetName = (pathBinder != null) ? pathBinder.value() : field.getName();
			valueMap.put(targetName, dtoValues[i]);

			// Resolve write converter
			if (pathBinder != null) {
				Function converter = resolveWriteConverter(dtoType, pathBinder, field);
				if (converter != null) {
					converterMap.put(targetName, converter);
				}
			}
		}

		// Build result array aligned with entity columns
		List<Path<?>> columns = entity.getColumns();
		Object[] result = new Object[columns.size()];
		for (int i = 0; i < columns.size(); i++) {
			String colName = columns.get(i).getMetadata().getName();
			if (valueMap.containsKey(colName)) {
				Object value = valueMap.get(colName);
				Function converter = converterMap.get(colName);
				if (converter != null && value != null) {
					value = converter.apply(value);
				}
				result[i] = value;
			}
			// else: leave as null (DTO doesn't have this field)
		}
		return result;
	}

	@SuppressWarnings("rawtypes")
	private static Function resolveWriteConverter(Class<?> dtoType, PathBinder pathBinder, Property field) {
		Class<? extends Function> writeClass = pathBinder.writeConverter();
		if (writeClass != Function.class) {
			return (Function) TypeUtils.newInstance(writeClass);
		}
		String ref = pathBinder.writeConverterRef();
		if (!ref.isEmpty()) {
			return Util.getStaticFunctionField(dtoType, ref, field.getName());
		}
		return null;
	}
}
