package com.github.xuse.querydsl.sql;

import java.sql.Connection;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.function.Supplier;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.config.ConfigurationEx;
import com.github.xuse.querydsl.sql.column.ColumnMapping;
import com.github.xuse.querydsl.sql.dml.SQLDeleteClauseAlter;
import com.github.xuse.querydsl.sql.dml.SQLInsertClauseAlter;
import com.github.xuse.querydsl.sql.dml.SQLMergeClauseAlter;
import com.github.xuse.querydsl.sql.dml.SQLUpdateClauseAlter;
import com.github.xuse.querydsl.sql.expression.AdvancedMapper;
import com.github.xuse.querydsl.sql.expression.AbstractMapperSupport;
import com.querydsl.core.QueryFlag.Position;
import com.querydsl.core.Tuple;
import com.querydsl.core.types.Expression;
import com.querydsl.core.types.ExpressionUtils;
import com.querydsl.core.types.Operation;
import com.querydsl.core.types.Path;
import com.querydsl.core.types.dsl.Expressions;
import com.querydsl.sql.RelationalPath;
import com.querydsl.sql.SQLOps;
import com.querydsl.sql.mysql.MySQLQuery;
import com.querydsl.sql.mysql.MySQLReplaceClause;

public class MySQLQueryFactory2 extends AbstractSQLQueryFactory<MySQLQuery<?>> {
    public MySQLQueryFactory2(ConfigurationEx configuration, Supplier<Connection> connection) {
        super(configuration, connection);
    }

    /**
     * Create a INSERT IGNORE INTO clause
     *
     * @param entity table to insert to
     * @return insert clause
     */
    public SQLInsertClauseAlter insertIgnore(RelationalPath<?> entity) {
        SQLInsertClauseAlter insert = insert(entity);
        insert.addFlag(Position.START_OVERRIDE, "insert ignore into ");
        return insert;
    }

    /**
     * Create a INSERT ... ON DUPLICATE KEY UPDATE clause
     *
     * @param entity table to insert to
     * @param clause clause
     * @return insert clause
     */
    public SQLInsertClauseAlter insertOnDuplicateKeyUpdate(RelationalPath<?> entity, String clause) {
    	SQLInsertClauseAlter insert = insert(entity);
        insert.addFlag(Position.END, " on duplicate key update " + clause);
        return insert;
    }


    /**
     * Create a INSERT ... ON DUPLICATE KEY UPDATE clause
     *
     * @param entity table to insert to
     * @param clauses clauses
     * @return insert clause
     */
    public SQLInsertClauseAlter insertOnDuplicateKeyUpdate(RelationalPath<?> entity, Expression<?>... clauses) {
        return insertOnDuplicateKeyUpdate(entity,true,clauses);
    }

    /**
     * Create a INSERT ... ON DUPLICATE KEY UPDATE clause and, when
     * {@code autoUpdateColumns} is {@code true}, automatically append the
     * {@code @AutoGenerated} columns that apply on update (e.g.
     * {@link com.github.xuse.querydsl.annotation.GeneratedType#UPDATED_TIMESTAMP}
     * and {@link com.github.xuse.querydsl.annotation.GeneratedType#VERSION}) to
     * the UPDATE part of the clause.
     * <p>
     * MySQL only touches the columns explicitly listed in {@code ON DUPLICATE KEY
     * UPDATE} when the UPDATE branch is taken, so without this the framework's
     * {@code @AutoGenerated} update columns are never refreshed on an upsert.
     * Columns already present in {@code clauses} are left untouched (the caller's
     * assignment wins).
     * <h3>中文</h3>
     * 创建 INSERT ... ON DUPLICATE KEY UPDATE 子句。当 {@code autoUpdateColumns} 为
     * {@code true} 时，自动把更新场景下生效的 {@code @AutoGenerated} 列（例如
     * UPDATED_TIMESTAMP、VERSION）追加到 UPDATE 部分。MySQL 命中唯一键走 UPDATE 分支时，
     * 只会更新 ON DUPLICATE KEY UPDATE 中显式列出的列，因此若不追加，框架的自动更新列
     * 在 upsert 时不会被刷新。已在 {@code clauses} 中显式指定的列不会被覆盖。
     *
     * @param entity table to insert to
     * @param autoUpdateColumns whether to auto append @AutoGenerated update columns
     * @param clauses caller supplied update assignments
     * @return insert clause
     */
    public SQLInsertClauseAlter insertOnDuplicateKeyUpdate(RelationalPath<?> entity, boolean autoUpdateColumns,
            Expression<?>... clauses) {
        SQLInsertClauseAlter insert = insert(entity);
        Expression<?>[] merged = autoUpdateColumns ? mergeAutoUpdateColumns(entity, clauses) : clauses;
        appendOnDuplicateKeyUpdate(insert, merged);
        return insert;
    }

    private void appendOnDuplicateKeyUpdate(SQLInsertClauseAlter insert, Expression<?>[] clauses) {
        StringBuilder flag = new StringBuilder(" on duplicate key update ");
        for (int i = 0; i < clauses.length; i++) {
            flag.append(i > 0 ? ", " : "").append("{").append(i).append("}");
        }
        insert.addFlag(Position.END, ExpressionUtils.template(String.class, flag.toString(), (Object[]) clauses));
    }

    /**
     * Append the @AutoGenerated columns that apply on update to the caller supplied
     * assignments, skipping any column the caller already assigned.
     */
    private Expression<?>[] mergeAutoUpdateColumns(RelationalPath<?> entity, Expression<?>[] clauses) {
        if (!(entity instanceof RelationalPathEx)) {
            return clauses;
        }
        Set<Path<?>> assigned = new LinkedHashSet<>();
        for (Expression<?> clause : clauses) {
            Path<?> target = targetOf(clause);
            if (target != null) {
                assigned.add(target);
            }
        }
        RelationalPathEx<?> ex = (RelationalPathEx<?>) entity;
        List<Expression<?>> result = new ArrayList<>(clauses.length + 2);
        for (Path<?> p : ex.getColumns()) {
            ColumnMapping metadata = ex.getColumnMetadata(p);
            AutoGenerated generated = metadata == null ? null : metadata.getGenerated();
            if (generated == null || assigned.contains(p)) {
                continue;
            }
            Object value = AdvancedMapper.asAutoValue(generated, metadata, AbstractMapperSupport.SCENARIO_UPDATE);
            if (value instanceof Expression<?>) {
                // build "column = value" directly to avoid ambiguous SQLExpressions.set overloads on raw Path
                result.add(Expressions.operation(p.getType(), SQLOps.SET_LITERAL, p, (Expression<?>) value));
            }
        }
        if(result.isEmpty()) {
        	return clauses;
        }
        //如果确认需要添加，再加上原先有的
        for (Expression<?> clause : clauses) {
            result.add(clause);
        }
        return result.toArray(new Expression<?>[0]);
    }

    /**
     * Extract the assignment target column from a {@code SQLExpressions.set/setValues}
     * expression so we can detect which columns the caller already updates.
     */
    private Path<?> targetOf(Expression<?> clause) {
        if (clause instanceof Operation<?>) {
            Operation<?> op = (Operation<?>) clause;
            if (!op.getArgs().isEmpty() && op.getArg(0) instanceof Path<?>) {
                return (Path<?>) op.getArg(0);
            }
        }
        return null;
    }

	@Override
	public final SQLInsertClauseAlter insert(RelationalPath<?> path) {
		return new SQLInsertClauseAlter(connection, configuration, path);
	}
	
    @Override
    public MySQLQuery<?> query() {
        return new MySQLQuery<Void>(connection, configuration.get());
    }

    public MySQLReplaceClause replace(RelationalPath<?> entity) {
        return new MySQLReplaceClause(connection.get(), configuration.get(), entity);
    }

    @Override
    public <T> MySQLQuery<T> select(Expression<T> expr) {
        return query().select(expr);
    }

    @Override
    public MySQLQuery<Tuple> select(Expression<?>... exprs) {
        return query().select(exprs);
    }

    @Override
    public <T> MySQLQuery<T> selectDistinct(Expression<T> expr) {
        return query().select(expr).distinct();
    }

    @Override
    public MySQLQuery<Tuple> selectDistinct(Expression<?>... exprs) {
        return query().select(exprs).distinct();
    }

	@Override
	public <T> MySQLQuery<T> selectFrom(RelationalPath<T> expr) {
		return select(expr).from(expr);
	}
	
    @Override
    public MySQLQuery<Integer> selectZero() {
        return select(Expressions.ZERO);
    }

    @Override
    public MySQLQuery<Integer> selectOne() {
        return select(Expressions.ONE);
    }

	@Override
	public SQLDeleteClauseAlter delete(RelationalPath<?> path) {
		return new SQLDeleteClauseAlter(connection, configuration,path);
	}

	@Override
	public final SQLMergeClauseAlter merge(RelationalPath<?> path) {
		return new SQLMergeClauseAlter(connection, configuration, path);
	}

	@Override
	public final SQLUpdateClauseAlter update(RelationalPath<?> path) {
		return new SQLUpdateClauseAlter(connection, configuration, path);
	}
}