package com.github.xuse.querydsl.sql;

import java.util.Collection;
import java.util.List;

import com.github.xuse.querydsl.annotation.InitializeData;
import com.github.xuse.querydsl.sql.column.ColumnMapping;
import com.github.xuse.querydsl.sql.dbmeta.Collate;
import com.github.xuse.querydsl.sql.dbmeta.Constraint;
import com.github.xuse.querydsl.sql.expression.BeanCodec;
import com.github.xuse.querydsl.sql.partitions.PartitionBy;
import com.querydsl.core.types.Path;
import com.querydsl.sql.RelationalPath;

/**
 * <h2>English:</h2>
 * Extended metadata storage class that can store optimized reflection objects.
 * <h2>Chinese:</h2>
 * 扩展后的元数据存储类，可以存储优化后的反射对象和额外的列信息。
 *
 * @author Joey
 * @param <T> the type of entity
 */
public interface RelationalPathEx<T> extends RelationalPath<T> {

	/**
	 * @return 获得Bean转换器。
	 */
	BeanCodec getBeanCodec();

	/**
	 * @param path path of column
	 * @return 获得指定列（字段）的元数据描述
	 */
	ColumnMapping getColumnMetadata(Path<?> path);

	/**
	 * Get path by field name.
	 * <p>根据Java字段名获得Path对象
	 * 
	 * @param name of the path.(not column name)
	 * @return Path
	 */
	Path<?> getColumn(String name);
	
	/**
	 * @return 获得所有带有@AutoGeneratedValue注解的列
	 */
	List<ColumnMapping> getAutoColumns();

	/**
	 * Get all constraints (including indexes).
	 * <p>获得各类约束（含索引）
	 * 
	 * @return collection of Constraint
	 */
	Collection<Constraint> getConstraints();

	/**
	 * @return 表的字符集
	 */
	Collate getCollate();
	
	/**
	 * @return 自增起始值，仅对支持的数据库有效
	 */
	int getAutoIncrementStartAt();

	/**
	 * @return 表注释
	 */
	String getComment();

	/**
	 * @return 表分区配置
	 */
	PartitionBy getPartitionBy();

	/**
	 * Retrieves the instance of initialization data.
	 * <p>
	 * This method is designed to provide access to shared initialization data that
	 * may be required by various parts of the application.
	 * The specific content and structure of the initialization data are
	 * encapsulated within the returned {@link InitializeData} object.
	 * 
	 * @return An {@link InitializeData} object containing the initialization data /
	 *         返回包含初始化数据的{@link InitializeData}对象
	 */
	InitializeData getInitializeData();
}
