package com.github.xuse.querydsl.entity;

import java.sql.Types;
import java.time.LocalDateTime;
import java.util.Map;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.CustomType;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.UnsavedValue;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;
import com.github.xuse.querydsl.entity.type.TestForJSONObjectType;
import com.github.xuse.querydsl.entity.type.TestForStringAsDateTimeType;
import com.github.xuse.querydsl.enums.Gender;
import com.github.xuse.querydsl.types.EnumByCodeType;

import lombok.Data;

@Data
@TableSpec(name = "AVS_USER_AUTHORITY", primaryKeys = "id",alias = "au")
public class AvsUserAuthority {

	@ColumnSpec(name = "ID", nullable = false, autoIncrement = true)
	@UnsavedValue(UnsavedValue.ZeroAndMinus)
	private int id;

	@ColumnSpec(name = "USER_ID", size = 64, nullable = false)
	private String userId;

	@ColumnSpec(name = "DEV_ID", size = 64)
	private String devId;

	@ColumnSpec(name = "CHANNEL_NO", size = 10)
	private Integer channelNo;

	@ColumnSpec(name = "AUTH_TYPE", size = 10)
	private Integer authType;

	@ColumnSpec(name = "AUTH_CONTENT", size = 256)
	private String authContent;

	@ColumnSpec(name = "CREATE_TIME", nullable = false,type = Types.TIMESTAMP)
	@AutoGenerated(GeneratedType.CREATED_TIMESTAMP)
	private LocalDateTime createTime;

	@ColumnSpec(name = "UPDATE_TIME", nullable = false,type=Types.TIMESTAMP)
	@CustomType(value = TestForStringAsDateTimeType.class, parameters = "MM/dd/yyyy HH:mm:ss")
	@AutoGenerated(value = GeneratedType.UPDATED_TIMESTAMP, writeback = true)
	private String updateTime;

	@ColumnSpec(name = "GENDER", size = 64,nullable = false, type=Types.TINYINT)
	@CustomType(EnumByCodeType.class)
	private Gender gender;

	@ColumnSpec(name = "MAP_DATA", type = java.sql.Types.VARCHAR, size = 512)
	@CustomType(TestForJSONObjectType.class)
	private Map<String, String> map;

	@ColumnSpec(name = "ASSERTS", type = java.sql.Types.VARCHAR, size = 256)
	@CustomType(TestForJSONObjectType.class)
	private CaAsset asserts;
}
