package com.github.xuse.querydsl.entity;

import java.io.Serializable;
import java.sql.Types;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.Map;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.CustomType;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.UnsavedValue;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.Comment;
import com.github.xuse.querydsl.annotation.dbdef.Key;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;
import com.github.xuse.querydsl.entity.type.TestForJSONObjectType;
import com.github.xuse.querydsl.enums.Gender;
import com.github.xuse.querydsl.lambda.DateLambdaColumn;
import com.github.xuse.querydsl.lambda.DateTimeLambdaColumn;
import com.github.xuse.querydsl.lambda.LambdaColumn;
import com.github.xuse.querydsl.lambda.LambdaTable;
import com.github.xuse.querydsl.lambda.NumberLambdaColumn;
import com.github.xuse.querydsl.lambda.SimpleLambdaColumn;
import com.github.xuse.querydsl.lambda.StringLambdaColumn;
import com.github.xuse.querydsl.sql.ddl.ConstraintType;

import lombok.Data;

/**
 * A database object without Q* class.
 */
@Data
@TableSpec(name="ca_foo",primaryKeys="id",collate = "utf8mb4_general_ci",
keys = {
		@Key(path= {"code"},type=ConstraintType.UNIQUE),
		@Key(path= {"content"},type=ConstraintType.FULLTEXT,allowIgnore = true),
	}
)
@Comment("Test table for Foo.")
public class Foo implements Serializable {

	public static final LambdaTable<Foo> foo = () -> Foo.class;

	public static final NumberLambdaColumn<Foo, Integer> _id = Foo::getId;

	public static final StringLambdaColumn<Foo> _code = Foo::getCode;

	public static final StringLambdaColumn<Foo> _name = Foo::getName;

	public static final StringLambdaColumn<Foo> _content = Foo::getContent;

	public static final DateTimeLambdaColumn<Foo, Instant> _created = Foo::getCreated;

	public static final DateTimeLambdaColumn<Foo, Date> _updated = Foo::getUpdated;

	public static final LambdaColumn<Foo, Gender> _gender = Foo::getGender;

	public static final SimpleLambdaColumn<Foo, TableDataTypes> _ext = Foo::getExt;

	public static final SimpleLambdaColumn<Foo, Map<String, String>> _map = Foo::getMap;

	public static final NumberLambdaColumn<Foo, Integer> _volume = Foo::getVolume;

	public static final NumberLambdaColumn<Foo, Integer> _version = Foo::getVersion;

	public static final NumberLambdaColumn<Foo, Integer> _codeType = Foo::getCodeType;

	public static final DateLambdaColumn<Foo, java.sql.Date> _inDay = Foo::getInDay;

	public static final DateLambdaColumn<Foo, LocalDate> _inDay2 = Foo::getInDay2;

	public static final DateLambdaColumn<Foo, LocalDate> _inDay3 = Foo::getInDay3;
	
	@ColumnSpec(autoIncrement = true,type = Types.INTEGER,unsigned = true,nullable = false)
	@Comment("primary key，auto increment.")
	private int id;
	
	@ColumnSpec(type = Types.VARCHAR,size=64,nullable = false,defaultValue = "''")
	@Comment("The code of asset. unique.")
	private String code;
	
	@ColumnSpec(name="asset_name",size=128,nullable = false)
	@Comment("The name of the asset.")
	private String name;
	
	@ColumnSpec(size=16384)
	@Comment("Asset's comments.")
	private String content;
	
	@ColumnSpec()
	@AutoGenerated(GeneratedType.CREATED_TIMESTAMP)
	@Comment("create time of the record.")
	private Instant created;
	
	@ColumnSpec()
	@AutoGenerated(value=GeneratedType.UPDATED_TIMESTAMP,overwrite = true)
	@Comment("update time of the record.")
	private Date updated;
	
	@ColumnSpec(type=Types.VARCHAR,size=16)
	@Comment("Another extension info.")
	private Gender gender;
	
	@CustomType(TestForJSONObjectType.class)
	@ColumnSpec(type=Types.VARCHAR,size=256)
	@Comment("extension info.")
	private TableDataTypes ext;
	
	@CustomType(TestForJSONObjectType.class)
	@ColumnSpec(type=Types.VARCHAR,size=256)
	@Comment("Some custom attributes.")
	private Map<String,String> map;
	
	@ColumnSpec(type=Types.INTEGER,nullable = false,unsigned = true, defaultValue = "0")
	@UnsavedValue(UnsavedValue.MinusNumber)
	private int volume = -1;
	
	@ColumnSpec(type=Types.INTEGER,nullable = false,unsigned = true,defaultValue = "1")
	@UnsavedValue(UnsavedValue.ZeroAndMinus)
	@AutoGenerated(GeneratedType.VERSION)
	private int version;
	
	@ColumnSpec(type=Types.INTEGER,nullable = false,defaultValue = "1")
	private int codeType;
	
	@ColumnSpec(type=Types.DATE)
	private java.sql.Date inDay;
	
	@ColumnSpec(type=Types.TIMESTAMP)
	private LocalDate inDay2;
	
	@ColumnSpec(type=Types.TIMESTAMP, size=3)
	private LocalDate inDay3;

}
