package com.github.xuse.querydsl.entity;

import java.util.Date;

import com.github.xuse.querydsl.annotation.AutoGenerated;
import com.github.xuse.querydsl.annotation.GeneratedType;
import com.github.xuse.querydsl.annotation.dbdef.ColumnSpec;
import com.github.xuse.querydsl.annotation.dbdef.Key;
import com.github.xuse.querydsl.annotation.dbdef.TableSpec;
import com.github.xuse.querydsl.sql.ddl.ConstraintType;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
@TableSpec(name="ca_foo_history",collate = "utf8mb4_general_ci",
keys = {
		@Key(path= {"code","version"},type=ConstraintType.UNIQUE),
	}
)
public class FooHistory extends Foo{
	@ColumnSpec()
	@AutoGenerated(GeneratedType.CREATED_TIMESTAMP)
	private Date modifyData;
	
	@ColumnSpec()
	private String action;
	
	@ColumnSpec()
	private String source;
}
